### ISSUE TITLE
Exception printed in Lwt_stream.bounded_push#close documentation

### ISSUE THREAD

**Issue by reynir** [ocsigen/lwt#1005]
This likely should be reported to the documentation tool.

In the documentation for the `close` method of `Lwt_stream.bounded_push` an exception is printed:
https://ocsigen.org/lwt/latest/api/Lwt_stream.bounded_push-c#METHODclose

```
Is a thread is blocked on Error a_api: exception Dune__exe__Api.Error("\"bounded_push\" is not a valid module name") ?
```

**Comment by raphael-proust** [comment]
Oh thanks for the report… not sure what went wrong there but I'll have a look some time
