### ISSUE TITLE
Lwt_io sometimes register threads that do not terminate in Lwt_main.at_exit

### ISSUE THREAD

**Issue by vbmithr** [ocsigen/lwt#114]
When calling Pervasives.exit, an Lwt program should always terminate. In some cases, it seems that the a program using Lwt_io is stuck forever, even after a Pervasives.exit.

**Comment by vouillon** [comment]
This is probably a duplicate of #48

**Comment by aantron** [comment]
Indeed most likely a duplicate, but answering here since both reporters are present :) See the attached commit for an explanation of the deadlock, if you are interested. Should be fixed now.
