### ISSUE TITLE
Lwt_sys.Not_available for system functions that are actually available

### ISSUE THREAD

**Issue by andrenth** [ocsigen/lwt#120]
Hello

Today I've done a clean reinstall of my opam packages. Since then I'm getting the error below with Lwt_unix:

    # let (a, b) = Lwt_unix.socketpair Lwt_unix.PF_UNIX Lwt_unix.SOCK_STREAM 0;;
    Exception: Lwt_sys.Not_available "unix_socketpair_stub".

Lwt version is 2.4.7 and it was configured by opam with

    ./configure --prefix /home/andre/.opam/4.02.1 --enable-libev --enable-camlp4 --enable-react --disable-ssl --enable-unix --enable-preemptive --disable-glib --enable-ppx

Any idea what could cause this?

Edit: All this is on Ubuntu 14.04.

Thanks,
Andre

**Comment by vouillon** [comment]
Indeed, a bug was introduced in the last release of Lwt...

**Comment by andrenth** [comment]
Thanks Jerome! Do you think a new version could be released with that fix?

**Comment by vouillon** [comment]
Indeed, we should schedule a new release soon.
