### ISSUE TITLE
Lwt_unix.sleep thread not waking up

### ISSUE THREAD

**Issue by zoggy** [ocsigen/lwt#121]
Hello,

I have a problem using Lwt_unix.sleep. I cannot reduce to a small example so I describe the observed behaviour, if someone can give me clues about what's going on.

I have various Lwt.t threads sleeping for 2 seconds, doing things, then waiting again, in a recursive function. At the beginning, everything is fine, threads wake up every 2 seconds, do what they have to do, then recursively call the function to sleep again and so on.

After some wake ups, there is a kind of pause during several seconds with no threads waking up (but going to sleep). Then they wake up again. Then pause again and then one of them is not waken up. After some time, another one is not waken up, then another one until no thread seems to be waken up.

Moreoever, I observe this when I have 2 or 4 threads, but everything is ok when I have 1 or 3. With 5 threads some disappear (don't seem to wake up), then reappear again...

Any idea of what could be wrong ?  

The problem is the same when the threads do nothing between the calls to Lwt_unix.sleep.

**Comment by zoggy** [comment]
Note: after switching to the libev engine, the problem does not appear.

Note also that on a dummy example, just running these sleeping threads, eveything is ok with the select engine. But the program where I encounter the problem described above also handles HTTP connections (using cohttp), so there might be a problem related to select ?

**Comment by zoggy** [comment]
I put at the following address a program showing the bug: http://pauillac.inria.fr/~guesdon/lwtsleep.ml
I just created sleeping threads and added a http server from a cohttp test file.
Compile with 
````ocamlfind ocamlopt -o lwtsleep -annot -package cohttp.lwt,lwt.unix -linkpkg lwtsleep.ml````
Just run ``./lwt``.
When commenting the ``Lwt_engine.set ...`` line to use libev if available, everything is ok.

**Comment by samoht** [comment]
I had exactly the same problem few days ago while trying to debug Irmin (also using cohttp), I was not able to track the cause of the bug but switching to libev seems to fix the issue.

**Comment by vouillon** [comment]
I have not been able to reproduce the issue with your test files (with Lwt 2.4.7, Cohttp 0.15.1 and Conduit 0.7.2). The six threads wake up every second as expected.

**Comment by zoggy** [comment]
The problem is not visible immediately. Eveything is fine during some seconds, then only some of the threads are waken up. Here the problem appears after 20-30 seconds.

**Comment by zoggy** [comment]
I just upgraded to Conduit 0.7.2 just in case (I already was with Lwt 4.2.7 and Cohttp 0.15.1) but the problem remains.

**Comment by avsm** [comment]
Bug reproduced on MacOS X 10.10. Investigating...

**Comment by avsm** [comment]
The bug can reproduced just by linked Conduit_lwt_unix. Very suspiciously, there are two different implementations of `Lwtsleep` with and without it:

```
-       3e7c641a41be13141ab036f00324fca1        Lwtsleep
+       369352892955c5fc726a1c1a65303381        Lwtsleep
```

Trying to find where this compilation unit came from now...

**Comment by avsm** [comment]
Ignore previous -- this was the main function! :)

**Comment by avsm** [comment]
The problem is in the OCaml TLS stack which is hooking into `Lwt_engine` to feed entropy:

```
let trickle period fd =
  let buf = Cstruct.create 4 in
  let _   =
    Lwt_engine.on_timer (float period) true @@ fun _ ->
      async @@ fun () ->
        prerr_endline "timer";
        Lwt_cstruct.(complete (read fd) buf) >|= fun () ->
(* BUG HAPPENS HERE and sleeping threads are lost *)
          Nocrypto.Rng.Accumulator.add_rr ~source:0 buf)
  in
```

**Comment by samoht** [comment]
Does ` Nocrypto.Rng.Accumulator.add_rr` can raise an exception? @pqwy ?

**Comment by avsm** [comment]
The bug happens without nocrypto.  I've distilled it down to two files:

foo.ml:
```
open Lwt

let () =                                                                                       
  let _ = Lwt_engine.on_timer 2.0 true @@ fun _ ->
      prerr_endline "on_timer";                              
  in ()
```

and the `bar.ml` of

```
open Lwt.Infix

let sleep_duration = 1.0
let debug = fun s -> Lwt_io.write Lwt_io.stderr (s^"\n")

let rec wait f =
  Lwt.catch
    (fun () ->
       debug (Printf.sprintf "sleeping for %f" sleep_duration) >>= fun () ->
         Lwt_unix.sleep sleep_duration >>= fun () ->
         debug "doing thing... " >>= fun _ ->
         f () >>= fun _ -> wait f
    )
    (fun e ->
       prerr_endline (Printf.sprintf "wait: %s" (Printexc.to_string e));
       wait f
    )
;;
let () = Lwt_engine.set (new Lwt_engine.select);;
Lwt_unix.run (Lwt.join
 [
   wait (fun () -> debug "thread 1") ;
   wait (fun () -> debug "thread 2") ;
   wait (fun () -> debug "thread 3") ;
   wait (fun () -> debug "thread 4") ;
   wait (fun () -> debug "thread 5") ;
   wait (fun () -> debug "thread 6") ;
 ])
```

If compiled with both linked in (so that the Lwt_engine calls both happen), e.g.

```
ocamlfind ocamlopt -annot -o lwtsleep -annot -package lwt.unix -linkpkg foo.ml bar.ml
```

**Comment by vouillon** [comment]
I found the issue. Timers are stored in a priority queue. Repeating timers gets their scheduled wake-up time modified while still in the queue, hence breaking the priority queue invariants...

**Comment by vouillon** [comment]
Thanks @zoggy and @avsm for investigating the issue!

**Comment by avsm** [comment]
Confirmed the bug has disappeared in master; thanks @vouillon!  Any chance of an Lwt point release?  This bug is hitting a lot of users due to the Cohttp/TLS default configuration using it.  I can also just splice the fix directly into opam-repository if you'd rather hold off on a release.

**Comment by avsm** [comment]
Would it be possible to cut a release of Lwt with this fix?  It's really affecting a lot of things with missing timers and deadlocks.

**Comment by vouillon** [comment]
You're right. We should make a release soon.

**Comment by avsm** [comment]
Thanks @vouillon!
