### ISSUE TITLE
Documentation for logging

### ISSUE THREAD

**Issue by kemaclachlan** [ocsigen/lwt#130]
The documentation for logging functions in lwt_log_core says that the default value of ~logger is  Lwt_log_core.​default. The documentation for this default value says `The default logger. It is used as default when no one is specified. Initially, it sends messages to the standard output for error messages`.  This value is null which means it doesn't send anything to the standard output. It would be nice if the documention mentioned it is actually null and you need a logger to be able to log anything.

**Comment by haesbaert** [comment]
Actually the default logger gets created in unix/lwt_unix.ml, like this:

let _ = Lwt_log_core.default := channel ~close_mode:`Keep ~channel:Lwt_io.stderr ()

So the documentation is indeed wrong, as it logs everything t **stderr** not **stdout**.
Ironically I found this out in parallel with your report. I've made pull request #140 to fix the documentation.

**Comment by Drup** [comment]
fixed.
