### ISSUE TITLE
Documentation of Lwt_unix.write appears to be misleading.

### ISSUE THREAD

**Issue by haesbaert** [ocsigen/lwt#133]
From lwt_unix.mli:
"write fd buf ofs len has the same semantic as Unix.write, but is cooperative"

unless I read the code wrong, there is one key difference with Lwt_unix.write regarding write on blocked fds. The Unix.write _never_ returns a shortcount, since it actually loops calling multiple writes, for the syscall semantic, there is Unix.write_single.

The Lwt_unix.write may return a short count on a blocked fd, this is a key difference if before (with the Unix.write mindset), you were never expecting short counts.

These are the differences I found
UNBLOCKING:
  Unix.write -> May return short count.
	      May return EAGAIN.
  Lwt_unix.write -> May return a short count.
	       	  Never returns EAGAIN.
BLOCKING:
  Unix.write -> Never returns a short count.
	      discards bytes written in case of an error
	      in a second write and returns the error.
  Lwt_unix.write -> May return a short count.
	       	  Correctly returns the error.
(not considering EAGAIN on the BLOCKING case since it is not allowed)

I'm new to ocaml, so forgive me if I understood something wrong.

**Comment by rneswold** [comment]
Why did you close this issue? Was the documentation updated? I've found the `Lwt_unix` documentation to be lacking; the author liked to point the reader to the `Unix` module for much of the API. This is cheating. Especially since you found that the `Unix` docs don't actually describe the behavior of `Lwt_unix`.

**Comment by haesbaert** [comment]
It was open for a while and no one seemed to be interested, I'm re-open since it seems to be a shared concern.
