### ISSUE TITLE
Error message describing use of *_LIBS var doesn't match implementation

### ISSUE THREAD

**Issue by wiml** [ocsigen/lwt#138]
If a C library isn't found, the configure process (in `discover.ml` apparently) emits a message saying that you can specify an include path or library search path in the environment:

    export LIBEV_LIBS=-L/opt/local/lib

However, in `discover.ml`, the variable that is overridden by the environment contains not just the linker search path flag (`-L...`), but also the library flag (`-lev`). In order to get lwt to compile you need to put both flags into LIBEV_LIBS:

    export LIBEV_LIBS='-L/foo/bar/lib -lev'

which goes against the error message. (Personally, I think the `*_LIBS` flag should instead be `*_LDFLAGS`, and `*_LIBS` should contain by default just the '-lev' and rarely need to be overridden. This is closer to the usual convention.)

**Comment by aantron** [comment]
Thanks!

I had a similar observation about `LDFLAGS` vs. `LIBS`, but I prefer not to change that at this point, unless it is causing problems for someone. Don't want to risk causing problems for someone *else*.
