### ISSUE TITLE
Lwt_log.syslog should not have to look for the syslog socket and just bind to syslog(3). Breaks OS X syslog.

### ISSUE THREAD

**Issue by haesbaert** [ocsigen/lwt#141]
Lwt_log.syslog_connect accepts a list of "possible syslog sockets to connect".
OS X for instance has it in /var/run/syslog. So it doesn't work unless I pass in the socket path. Adding the OS X path seems like a bad idea, as it is just the case for waiting until a system uses the socket elsewhere.

Is there any special reason for doing this manually instead of just using the libc bindings ?
That would respect POSIX and work pretty much everywhere, syslog doesn't even need to be implemented across unix sockets, what should be respected is the syslog API. 
The knowledge of knowing "how to connect to the machine syslog" is in syslog(3) and should not be in lwt.

Again, there might be a special requirement which I'm missing.

**Comment by hcarty** [comment]
Would it be acceptable to add /var/run/syslog to the list of checked sockets, at least as a short-term solution?

**Comment by haesbaert** [comment]
I think so, I was waiting on a comment to maybe rewrite it and rely on the libc bindings.

**Comment by vasilisp** [comment]
I would presume that the libc bindings can block, in which case they cannot be used. But this is just a guess.

**Comment by haesbaert** [comment]
I don't think so, it's quite easy to wrap a syscall that may block in Lwt.
The code is derived from ocaml-syslog, I guess it was just used whatever was at hand at the time.

**Comment by aantron** [comment]
A PR for using `syslog(3)` is welcome, if still interested. One thing to watch out for, however, is Win32 compatibility: http://stackoverflow.com/questions/9496129/cannot-find-syslog-h-on-windows

It seems that the current `syslog` logger couldn't work on Win32 anyway (haven't tested), so it should be fine to just not support it – as long as Lwt still compiles on Win32.

I think I would wait until we are doing CI at least on MinGW, though, before merging any such PR.

**Comment by aantron** [comment]
`Lwt_log` was moved to [another repo](https://github.com/ocsigen/lwt_log) in #511, and is deprecated in favor of [`Logs_lwt`](https://erratique.ch/software/logs/doc/Logs_lwt.html).
