### ISSUE TITLE
Dubious compare and hash functions for libev loop wrapper objects

### ISSUE THREAD

**Issue by mark-christiaens** [ocsigen/lwt#146]
In lwt_libev_stubs.c there is code to implement the hash and compare functions for the wrapper object for a libev loop structure (similar issues exists for the watcher structure):
```c
static int compare_loops(value a, value b)
{
  return (int)(Data_custom_val(a) - Data_custom_val(b));
}

static long hash_loop(value loop)
{
  return (long)Data_custom_val(loop);
}

static struct custom_operations loop_ops = {
  "lwt.libev.loop",
  custom_finalize_default,
  compare_loops,
  hash_loop,
  custom_serialize_default,
  custom_deserialize_default
};
```
If I read the OCaml code correctly then Data_custom_val will give you a pointer into an ocaml object: 
```c
#define Data_custom_val( v ) ((void *) &Field(( v ), 1))
```
This pointer will change when compaction occurs making the compare and hash functions return different results.  This could mess seriously with any data structures that rely on ordering or identity like maps, hash tables, sorted lists ...  

I think the intent of the code was to use the C-structs pointer as a basis for calculating the hash and the comparison but that is not what the code is doing. 

I tried to verify whether this code actually gets triggered: I attached a debugger to a running process and put some breakpoints in these functions but they were not hit in my small test.  If this is indeed dead code, should it not simply be removed?

**Comment by aantron** [comment]
Indeed, thanks for catching and reporting this. I don't think these functions are used, but I'd rather not remove them right now. I've yet to thoroughly consider `Lwt_engine`, and having these preserves some flexibility with what data structures can be used.
