### ISSUE TITLE
Not Found for pdf manual

### ISSUE THREAD

**Issue by heidi-ann** [ocsigen/lwt#147]
This page for downloading the manual as a pdf no longer works http://ocsigen.org/lwt/2.4.8/files/manual.pdf

**Comment by joncfoo** [comment]
On this page: http://ocsigen.org/lwt/2.5.1/manual/manual  the link to the PDF is also broken (http://ocsigen.org/lwt/2.5.1/files/manual.pdf)

**Comment by aantron** [comment]
New maintainer here; I'm inclined to drop support for the PDF manual completely, and instead make the web docs better. Please let me know if you have any objections or considerations (for example, you may prefer a single-web-page version of the docs to be available, so you can search through it easily, as with PDF).
