### ISSUE TITLE
LWT_NOT_AVAILABLE6 is not defined

### ISSUE THREAD

**Issue by camlspotter** [ocsigen/lwt#161]
Compilation of lwt-2.4.7 in MinGW OCaml fails:

```
In file included from src/unix/lwt_unix_stubs.c:95:0:
src/unix/lwt_unix_windows.c:521:1: warning: return type defaults to 'int' [-Wreturn-type]
 LWT_NOT_AVAILABLE6(unix_bytes_sendto)
 ^
src/unix/lwt_unix_windows.c: In function 'LWT_NOT_AVAILABLE6':
src/unix/lwt_unix_windows.c:522:1: error: expected declaration specifiers before 'LWT_NOT_AVAILABLE6'
 LWT_NOT_AVAILABLE6(unix_madvise)
 ^
```

This is easily fixable by adding `LWT_NOT_AVAILABLE6` to `lwt_unix.h`.

**Comment by aantron** [comment]
Apparently fixed in #117 by 07db8ae414db591902e5b6d6019c5334609bbb47, which was included in 2.4.8. The problem [no longer occurs](https://ci.appveyor.com/project/aantron/lwt/build/127/job/w85ftfr9dyee09te).
