### ISSUE TITLE
ocaml setup.ml -configure --disable-unix fails

### ISSUE THREAD

**Issue by camlspotter** [ocsigen/lwt#162]
This is not a real problem but `--disable-unix` seems not working (at least in MinGW OCaml):

```
$ ocaml setup.ml -configure --disable-unix
E: Cannot find buildable internal library 'lwt-unix' when checking build depends
E: Failure("1 configuration error")
```

**Comment by aantron** [comment]
This is worked around by running `make distclean` first. Happens on OS X as well, and most probably all systems.
