### ISSUE TITLE
Lwt_process.exec should support a chdir option

### ISSUE THREAD

**Issue by michipili** [ocsigen/lwt#163]
Sometimes we need to start a background process in a specific directory – containing resources or whatever else. It would be very easy to support in `Lwt_process.exec` by just adding an optional `chdir` in the appropriate branch of the fork. If we do not want to support this in `Lwt_process.exec` this leads to absurd complications because a the current working directory must be protected by a global _mutex_ and every part of the application needs to collaborate on it – esp. third party libraries creating files must be wrapped.

**Comment by talex5** [comment]
Example of this hack being used in DataKitCI:

https://github.com/docker/datakit/blob/1fecf15acfab7512042739ebbe62f432cc347382/ci/src/cI_process.ml#L28
