### ISSUE TITLE
lwt 2.4.7: Build fails on MinGW OCaml, lacking symbols

### ISSUE THREAD

**Issue by camlspotter** [ocsigen/lwt#164]
Example `unix/logging` fails to build, lacking `lwt_unix_wait4` and `lwt_unix_bytes_recvfrom`.  Adding them to `lwt_unix_windows.c` as `LWT_NOT_AVAILABLE*(*)` fixes the problem:

```
''C:/ocamlmgw/bin/ocamlfind.EXE ocamlopt -linkpkg -g -I src/unix -linkpkg -package unix -package bytes -package bigarray -package camlp4.quotations.o -package camlp4.extend -package camlp4 syntax/lwt-syntax.cmxa src/core/lwt.cmxa src/logger/lwt-log.cmxa src/unix/lwt-unix.cmxa examples/unix/logging.cmx -o examples/unix/logging.native
** Cannot resolve symbols for src/unix/lwt-unix.a(lwt_unix.o):
 _lwt_unix_wait4
** Cannot resolve symbols for src/unix/lwt-unix.a(lwt_bytes.o):
 _lwt_unix_bytes_recvfrom
```

Probably you should review `lwt_unix_windows.c` to see whether all the other unix functions are defined in it.

**Comment by aantron** [comment]
These particular functions were covered by 07db8ae414db591902e5b6d6019c5334609bbb47 in #117, released in 2.4.8. The example does build now.
