### ISSUE TITLE
Lwt on FreeBSD doesn't install lwt.syntax

### ISSUE THREAD

**Issue by ffreling** [ocsigen/lwt#176]
I installed lwt 2.4.7 on FreeBSD 10.1 with opam 1.2.2 without any issue.

But when I want to install another package with a lwt dependency (irc-client for instance), I have the following error:

    ### stderr ###
    # ocamlfind: Package `lwt.syntax' not found
    # W: Field 'pkg_lwt_syntax' is not set: Command ''/home/fab/.opam/system/bin/ocamlfind' query -format %d lwt.syntax > '/tmp/oasis-225b46.txt'' terminated with error code 2
    # E: Cannot find findlib package lwt.syntax
    # E: Failure("1 configuration error")
    # gmake: *** [setup.data] Error 1

I can't find any `lwt-syntax.*` in `~/.opam/system/lib/lwt/`
Any idea what might be the issue?

Thanks!

**Comment by Drup** [comment]
Do you have camlp4 installed ?

**Comment by ffreling** [comment]
I did not but installing camlp4 indeed fixed my issue.
Thanks.
