### ISSUE TITLE
Is LWT misconfigured in OPAM 1.2.x

### ISSUE THREAD

**Issue by rneswold** [ocsigen/lwt#177]
I have OPAM 1.2.0 installed. When I try to install `lwt`, I get:

```
$ opam install lwt
Your request can't be satisfied:
  - lwt.2.4.5 is in conflict with ssl.0.5.0

No solution found, exiting
```

`opam info lwt` shows version 2.5.0 is available (along with many other versions) but when I try to install it, I get:

```
$ opam install lwt.2.5.0
Your request can't be satisfied:
  - No package matches lwt.

No solution found, exiting
```

I get the same error if I try to install version 2.4.8. This seems like the OPAM config for `lwt` may have a bug. Can anyone else install the latest `lwt` using OPAM 1.2.x?

**Comment by vbmithr** [comment]
On 29/07/2015 17:15, Rich Neswold wrote:
> I get the same error if I try to install version 2.4.8. This seems like
> the OPAM config for |lwt| may have a bug. Can anyone else install the
> latest |lwt| using OPAM 1.2.x?

Be sure to have the cmdline tool "aspcud" installed on your machine.
OPAM does not work without it and its internal solver will return absurd
solution like this.

**Comment by rneswold** [comment]
> Be sure to have the cmdline tool "aspcud" installed on your machine.

I didn't dig down in the OPAM web pages enough to realize I needed to supply an external solver. Thanks for the pointer; I'll give it a try.

**Comment by amirmc** [comment]
Can you share any information on what system you're using?  I ask because for Mac users, installing `opam` via homebrew will also install `aspcud`.

**Comment by rneswold** [comment]
I'm using [NetBSD](http://www.netbsd.org) 6.1.4, which uses [PkgSrc](http://www.pkgsrc.org). There isn't a package for `aspcud` available, so I'd have to build it myself (along with `cmake`, `clasp`, `gringo`, and a few others.) Instead, I'm using the [CUDF Solver Farm](http://cudf-solvers.irill.org/index.html), which works great!

**Comment by gasche** [comment]
I recently pestered the OPAM upstream into adding some more documentation on what external solvers are for and how to use them: [Before you get started: "external solvers"](http://opam.ocaml.org/doc/Usage.html#Beforeyougetstartedquotexternalsolversquot). Any feedback on what additional things it should say, or another place it should be to be more helpful, would be appreciated.

**Comment by rneswold** [comment]
> I recently pestered OPAM upstream (in the person of Louis Gesbert) into adding some more documentation on what external solvers are for and how to use them: Before you get started: "external solvers".

That helps, thanks. The [Specifying Solver Preferences](http://opam.ocaml.org/doc/Specifying_Solver_Preferences.html) page also helped me find the Solver Farm solution, which saved me the effort of building/installing/maintaining a solver on my system.

**Comment by hcarty** [comment]
@gasche It would be nice to have links to the upstream solver sites and either instructions on how to tell opam to use a particular external solver (command line `--solver` vs `$OPAMEXTERNALSOLVER` in the environment).  A brief note on why aspcud is recommended over the other would be helpful too as the other two options look much simpler to build from source.
