### ISSUE TITLE
Lwt.protected listeners are not removed from the protected thread on cancel

### ISSUE THREAD

**Issue by mfp** [ocsigen/lwt#181]
It is rather easy to expect `Lwt.protected` to work like `choose` or `pick` (which remove listeners) and keep adding listeners accidentally to an existing thread when wrapping it with `Lwt.protected`. This could happen if the user does for example something resembling `match_lwt Lwt.pick [Lwt.protected t; Lwt_unix.sleep t0 >> raise_lwt Timeout]` (where the `t` thread is not canceled on timeout, but the timeout thread is on completion).

Iow., is there a reason for the following not to run in constant mem?

    let () =
      Lwt_main.run begin
        let t, _ = Lwt.wait () in
        Lwt.on_cancel t (fun () -> print_endline "CANCEL 1");

        let rec loop () =
          let t' = Lwt.bind (Lwt.protected t) @@ fun () ->
                   Lwt.return @@ print_endline "X"
          in
            Lwt.cancel t';
            loop ()
        in
          loop ()
      end

**Comment by aantron** [comment]
Thanks, this was a bug. If interested, see the message of the attached commit for details.

**Comment by mfp** [comment]
On Tue, Jun 28, 2016 at 06:26:48PM -0700, Anton wrote:
> Closed #181 via 616168f4669adb82b2cec9d1dece1da920a25242.

Thank you.

I'm adding for the record (to help future readers looking for help on memory
issues with the currently released Lwt versions) that this also solves
memleaks in Lwt_stream (peek, and probably more functions).

-- 
Mauricio Fernández

**Comment by aantron** [comment]
Thanks. Indeed. See, for instance, #56 (also fixed by the commit).
