### ISSUE TITLE
Problem with Lwt.with_value and Lwt_preemptive.detach

### ISSUE THREAD

**Issue by zoggy** [ocsigen/lwt#182]
Hello,

I encounter some problem when using Lwt.{get,with_value} and Lwt_preemptive.detach. Here is a simple program showing the problem:
````ocaml
let v = Lwt.new_key ()
let check () =
  match Lwt.get v with
    None -> failwith "Key not set!"
  | Some n -> prerr_endline (Printf.sprintf "Key set to %d" n)

let f () = check(); check(); check()

let test n =
  Lwt.with_value v (Some n) (Lwt_preemptive.detach f)

let () = Lwt_main.run
  (Lwt.join
   [ test 0 ; test 10 ; test 100 ; test 1000 ; test 10_000 ])
````
When run, this gives something like:
````
Key set to 10000
Key set to 1000
Key set to 100
Key set to 1000
Key set to 10
Fatal error: exception Failure("Key not set!")
````
i.e. the value of the key is changed during the execution of the detached function. It seems like a bug as it does not conform to what is expected from the documentation. Is there a workaround ?

**Comment by dsheets** [comment]
I believe the issue is with your use of `prerr_endline` here which under the hood calls `flush` which calls `write` after releasing the OCaml runtime lock. When the runtime lock is released by one thread, another can acquire it. Because you are using a single `Lwt.key` for multiple OS threads, this value gets mutated unexpectedly. `Lwt.key` is *lwt thread-local storage* and is not *OS thread-local storage*.

There is something strange with `Lwt.key` set to the value `0`, though.

Here is the program I used in the top-level:

```ocaml
let r = ref [] in
let v = Lwt.new_key () in
let check k = match Lwt.get v with
  | None -> r := (k,666)::!r
  | Some n -> r := (k,n)::!r
in
let f k () = check k; check k; check k in

let test n =
  Lwt.with_value v (Some n) (Lwt_preemptive.detach (f n))
in
Lwt.(
  join [ test 0 ; test 10 ; test 100 ; test 1000 ; test 10_000 ]
  >>= fun () -> return r
);;
- : (int * int) list ref =
{contents =                                                                       
  [(0, 666); (0, 666); (0, 666); (10, 10); (10, 10); (10, 10); (100, 100);
   (100, 100); (100, 100); (1000, 1000); (1000, 1000); (1000, 1000);
   (10000, 10000); (10000, 10000); (10000, 10000)]}
```

**Comment by zoggy** [comment]
> Lwt.key is lwt thread-local storage and is not OS thread-local storage.

This was not clear to me from the doc, but after looking at the implementation is was :-)
I ended up with a hashtable to store keys associated to OS thread ids, in complement of lwt thread keys.

If I understand correctly, you should not use lwt thread-local storage from detached threads.

**Comment by dsheets** [comment]
I believe `Lwt_preemptive.detach` runs a plain OCaml function without any lwt mechanism. If you want this detached OS thread to run something in the lwt main loop, you need to use `Lwt_preemptive.run_in_main` which accepts an `'a Lwt.t`. Releasing the run-time lock in another thread without telling lwt somehow will probably violate lwt's invariants on interleaving and mutation. I don't know whether lwt thread-local storage is retained through a `detach => run_in_main` sequence. It is perhaps something to test but I'm not sure how amenable the developers will be to ensuring it works correctly as `detach` signifies your dropping out of lwt to use the OS thread primitives.

**Comment by zoggy** [comment]
I used `detach` and `run_in_main` and indeed the lwt thread-local storage is not retained, so I used maps from OS thread ids to values, and when running `run_in_main` I use the `Lwt.with_value` to put the value associated to OS thread in a lwt thread-local key.

What I pass this way from lwt-threads to OS-threads and from OS-threads to lwt-threads is information for logging, to build some kind of call tree.

**Comment by aantron** [comment]
Thanks for the report and discussion. Indeed, Lwt thread-local storage should not be used from detached threads, and you cannot safely do `Lwt.get` across a `detach`. Changing this seems quite involved, so I've documented it for the time being.
