### ISSUE TITLE
Add function to clear Lwt_pool.t

### ISSUE THREAD

**Issue by hcarty** [ocsigen/lwt#183]
It would be useful to be able to clear the contents of a connection pool, for example, if the target host changes during the lifetime of a program.

**Comment by aantron** [comment]
It seems that the existing interface almost allows this using `~validate` and a bit of state, except that `~validate` is called on the next resource acquire, instead of resource release. Is/was that a problem for your usage? Is this still a problem now?

**Comment by hcarty** [comment]
I was working on a project I'm not longer involved with when I submitted the ticket.  Using `~validate` was a problem at the time but I don't recall why.  We can close this for now as any uses that I have now could work with some external state.
