### ISSUE TITLE
Lwt_preemtive: exception from Event module

### ISSUE THREAD

**Issue by smondet** [ocsigen/lwt#186]
Saw this backtrace in my logs:

```
Thread 1 killed on uncaught exception Invalid_argument("index out of bounds")
Raised by primitive operation at file "event.ml", line 93, characters 4-20
Called from file "src/preemptive/lwt_preemptive.ml", line 79, characters 17-63
Called from file "thread.ml", line 37, characters 8-14
Thread 2 killed on uncaught exception Invalid_argument("index out of bounds")
Raised by primitive operation at file "event.ml", line 93, characters 4-20
Called from file "src/preemptive/lwt_preemptive.ml", line 79, characters 17-63
Called from file "thread.ml", line 37, characters 8-14
```

There actually is an array access at that line in `Event` module:
https://github.com/ocaml/ocaml/blob/trunk/otherlibs/systhreads/event.ml#L93

It's called there:
https://github.com/ocsigen/lwt/blob/master/src/preemptive/lwt_preemptive.ml#L79

Is this expected behavior from the standard library?

What does it mean if not?

**Comment by fdopen** [comment]
I've observed this issue as well. I think it's a bug inside the OCaml standard library, not lwt.
Sometimes `Condition.wait` ( https://github.com/ocaml/ocaml/blob/53fff352723eddd14baac86bc5fd187b4c74223b/otherlibs/systhreads/event.ml#L87 ) finishes, although no other thread has called `Condition.signal` ( https://github.com/ocaml/ocaml/blob/53fff352723eddd14baac86bc5fd187b4c74223b/otherlibs/systhreads/event.ml#L234 ). Then `!performed` will be `-1` and this out of bound exception is thrown.

My guess: a spurious wakeup that isn't handled
https://en.wikipedia.org/wiki/Spurious_wakeup
http://pubs.opengroup.org/onlinepubs/007908775/xsh/pthread_cond_wait.html ( `Condition.wait` is a wrapper around `pthread_cond_wait` )

**Comment by fdopen** [comment]
I've reported it here: http://caml.inria.fr/mantis/view.php?id=7013
See: https://github.com/ocaml/ocaml/commit/307f55ade9a4376e890405f26e7730512d552551

**Comment by smondet** [comment]
Thank you!

Since this has never been a `Lwt_preemtive` issue, so I'm closing it.
