### ISSUE TITLE
Weird interaction between `Unix.create_process` and `Lwt_daemon`/`Lwt_io`

### ISSUE THREAD

**Issue by smondet** [ocsigen/lwt#189]
This is the code:

``` ocaml
let read_command_output_no_lwt_exn cmd =
  let ic = Unix.open_process_in cmd in
  let buf = Buffer.create 24 in
  begin try
    while true do
      Buffer.add_char buf (input_char ic)
    done
  with End_of_file -> ()
  end;
  begin match Unix.close_process_in ic with
  | Unix.WEXITED 0 -> Buffer.contents buf
  | _ -> failwith (Printf.sprintf "failed command: %S" cmd)
  end

let () =
  let open Printf in
  let open Lwt in
  let _ =
    match Sys.argv.(1) with
    | "issue" -> read_command_output_no_lwt_exn "ls"
    | no_issues-> "hey !"
  in
  Lwt_daemon.daemonize ~stdin:`Keep ~stdout:`Keep ~stderr:`Keep ~directory:"/" ();
  Lwt_main.run begin
    eprintf "Starting !\n%!";
    Lwt_io.printf "lwt-io 1.\n%!"
    >>= fun () ->
    Lwt_io.printf "lwt-io 2.\n%!" >>= fun () ->
    Lwt_io.with_file "/etc/passwd" ~mode:Lwt_io.input (fun inp ->
        eprintf "File opened !\n%!";
        Lwt_io.read inp
        >>= fun res ->
        eprintf "File read !\n%!";
        return ()
      )
    >>= fun () ->
    Lwt_io.printf "lwt-io 3.\n%!" >>= fun () ->
    return ()
```

If the `read_command_output_no_lwt_exn` gets used, openning the file seems to block forever.

```
 $ ocamlfind ocamlopt -package "lwt.unix" draft.ml -linkpkg -o lwtissue && ./lwtissue issue
Starting !
lwt-io 1.
lwt-io 2.
```

(Sometimes `File opened !` is also displayed but never `File read !`).

while when we don't use `Unix.create_process` everything else works:

```
 $ ocamlfind ocamlopt -package "lwt.unix" draft.ml -linkpkg -o lwtissue && ./lwtissue issuenot
Starting !
File opened !
lwt-io 1.
lwt-io 2.
File read !
lwt-io 3.
```

Without `Lwt_daemon.daemonize` it also works OK.

Using a `Lwt_io.output` and `Lwt_io.write` has the same effect (blocking forever).

(Using Lwt 2.4.8, same behavior on MacOSX and CentOS)

**Comment by smondet** [comment]
Just confirming that the issue is there with both engines `` (Lwt_sys.have `libev)`` `= true` or `= false`, thanks to the `conf-libev` package.

**Comment by aantron** [comment]
Since `Lwt_daemon` is now factored out of Lwt and deprecated, I am closing this. Please feel free to reopen if it still needs to be fixed.

See https://github.com/ocsigen/lwt/pull/484#issuecomment-338184730 about daemonization in general, and the rest of that issue for the fate of `Lwt_daemon`.
