### ISSUE TITLE
strange failure on timeouted sub-process

### ISSUE THREAD

**Issue by c-cube** [ocsigen/lwt#195]
```ocaml
Lwt_process.with_process_full ~timeout:3. ("sleep", [| "sleep"; "5" |]) 
  (fun p -> Lwt_io.read p#stdout )
|> Lwt_main.run;;
```

This piece of code should, I think, read and return "" after 3 seconds (the sub-process timeouts). What I get instead is an uncaught `CamlinternalLazy.Undefined`.

**Comment by fxfactorial** [comment]
Yep, just tried this and indeed got this exception.

**Comment by c-cube** [comment]
I tried to look at the code, but without a backtrace I really can't see where it comes from. All I get is

> Fatal error: exception CamlinternalLazy.Undefined
> Raised at file "src/core/lwt.ml", line 789, characters 22-23
> Called from file "src/unix/lwt_main.ml", line 34, characters 8-18

**Comment by diml** [comment]
I have an idea what it could be; the close operation of a process is a lazy:

```ocaml
class virtual common timeout proc channels =
  let wait = waitproc proc in
  let close = lazy(Lwt.join (List.map Lwt_io.close channels) >>= fun () -> wait) in
object(self)
  ...
  method close = Lwt.protected (Lazy.force close) >|= status
  ...
end
```

1. when the timeout expires `close` is forced
2. forcing `close` causes `p#stdout` to be closed (it's part of `channels`)
3. `Lwt_io.close` will wakeup the `Lwt_io.read p#stdout` thread with the exception `Channel_closed`
4. the thread is woken up immediately with the exception, causing the finalizing code of `Lwt_process.with_process_full` to be executed immediately
5. `Lwt_process.with_process_full` calls `p#close`, which forces `close`

There are severals ways to fix this issue:

- not using a lazy for close and manage the state explicitely:

  ```ocaml
  val mutable closed = false
  method close = if closed then self#status else (close <- true; ...)
  ```

- not waking up the thread immediately in `Lwt_io.close`:

  ```
  Lwt.on_success (Lwt_unix.yield ()) (fun () -> wakeup_exn blah x)
  ```

The second solution might be better as the current behavior is a bit unexpected for users.
