### ISSUE TITLE
usefullness of Lwt_io.establish_server

### ISSUE THREAD

**Issue by zoggy** [ocsigen/lwt#196]
Hello,

The type of `Lwt_io.establish_server` is the following:
````ocaml
val establish_server : 
  ?fd:Lwt_unix.file_descr ->
  ?buffer_size:int ->
  ?backlog:int ->
  Unix.sockaddr ->
  (input_channel * output_channel -> unit) ->
  server
````
The function `f` handling connections is supposed to return `unit` instead of `unit Lwt.t`. Is this intended ? With this type, `establish_server` is useless, since using the channels requires using Lwt_io functions. Looking at the implementation, the server does not accepted any other request during the execution of `f`. This is not very Lwt-ish.

**Comment by diml** [comment]
I wrote this signature, the intent was for the callback to start some computation in the background and return immediately. You can use `Lwt.async` for instance

**Comment by zoggy** [comment]
Hum, ok.
