### ISSUE TITLE
Release tarballs should not contain OASIS binaries

### ISSUE THREAD

**Issue by cakeplus** [ocsigen/lwt#204]
Latest release tarballs include a very large (3 megabyte) `setup-dev.exe` binary. I assume it was accidental. Would send a pull request if there were release branches (github doesn't allow to make a PR on a tag).

https://github.com/cakeplus/lwt/tree/2.5.1-fix

**Comment by Drup** [comment]
Hum, `dist.sh` should prevent this kind of issue. @vbmithr ?

**Comment by vbmithr** [comment]
I probably screw it up. Let me some time to figure that out. I don't even remember if I used `dist.sh` or not. Apologies, anyway :)
