### ISSUE TITLE
lwt_result module?

### ISSUE THREAD

**Issue by c-cube** [ocsigen/lwt#226]
Since `result` is now a standard type, it would be nice to have a helper module to deal with `('a, 'b) result Lwt.t` (same as what `Lwt_list` does for lists). I can contribute an initial implementation is needed.

**Comment by hcarty** [comment]
I have one that I've been using internally.  I'd be happy to share that as well.

**Comment by c-cube** [comment]
I suspect many people do :-)

**Comment by Drup** [comment]
Note that `Lwt.t` already contains a result type. There is also `Lwt.result`, which is isomorph to `('a, exn) result` (yes, without Lwt.t).

I think we could make `Lwt.result` really a result and add your module. @diml ?

**Comment by diml** [comment]
Having `'a Lwt.result` be `('a, exn) result` seems right. Right now the `'a result -> 'a thread_state` operation would be less efficient with this equality, but eventually maybe the compiler could see it's the same thing. Anyway this optimization probably doesn't matter; in Lwt this type is used only in `Lwt_unix` and `Lwt_preemptive` and in both cases it wouldn't be a problem to not have the optimization

**Comment by aantron** [comment]
Proposed implementations are welcome, especially ones informed by recent discussions on usage of result types.

**Comment by aantron** [comment]
Added in #247.
