### ISSUE TITLE
Lwt_unix.bind should be in the monad

### ISSUE THREAD

**Issue by dsheets** [ocsigen/lwt#230]
``` ocaml
Lwt_unix.(bind sock (ADDR_UNIX sock_path)) : unit
```

could block indefinitely due to FS `mknod` on `sock_path`.

**Comment by aantron** [comment]
Agreed. Seems like it would have to wait for a major release though, unless there is some way to change this gracefully without breaking existing code, and still end up with the name `bind`.

**Comment by dmbaturin** [comment]
I'd like a way to use the new blocking version immediately in the code where I use UNIX domain sockets.
