### ISSUE TITLE
Supporting the brand new type result. 

### ISSUE THREAD

**Issue by mmaker** [ocsigen/lwt#242]
How about creating `return_ok` and `return_error` in Lwt, to behave pretty much the same as `return_nil`, `return_some`, `return_true` & co.?

<https://github.com/mmaker/ocaml-acme/commit/2478f9a0afddb2d1c5f8e0b746bcac0098644dc3>

**Comment by Drup** [comment]
Related: https://github.com/ocsigen/lwt/issues/226

**Comment by aantron** [comment]
[Done](https://github.com/ocsigen/lwt/blob/b0290579016d22520f23764b15ae74efec47b640/src/core/lwt.mli#L124) in #247.

**Comment by mmaker** [comment]
♥
