### ISSUE TITLE
Lwt_preemptive should document how to compile programs that use it

### ISSUE THREAD

**Issue by hcarty** [ocsigen/lwt#245]
Users need to add `threads` as a tag in ocamlbuild or do the equivalent from another build system, otherwise odd compilation errors happen.

**Comment by aantron** [comment]
Thanks! Relevant discussion: http://irclog.whitequark.org/ocaml/2016-05-17#16483826;

**Comment by aantron** [comment]
cc @hcarty @fxfactorial Please glance at the attached commit :)

To answer a question from IRC discussion, we can provide the `-thread` flag automatically *during linking* using `META`, I think. See the [docs](http://projects.camlcity.org/projects/dl/findlib-1.6.2/doc/ref-html/r721.html), namely the `linkopts` variable and predicates `mt_posix`, `mt_vm`. However, I'm under the impression that it also has to be provided during the *compilation* of the user's other modules, and I don't think there is a way to require that through `ocamlfind`.

And, as mentioned, `META` doesn't help people who may, hypothetically, not be using `ocamlfind`.

**Comment by hcarty** [comment]
Looks good to me!

**Comment by fxfactorial** [comment]
Why not add a comment about adding `threads` to `BuildDepends` for oasis.

**Comment by aantron** [comment]
I think `BuildDepends` is for packages, but `-thread` is a compiler flag. AFAIK you have to add to `_tags` with OASIS as well. Is that what you had to do? Perhaps we should say "For OCamlbuild or OASIS..."?

**Comment by hcarty** [comment]
I think @fxfactorial is correct about the oasis configuration. It shouldn't require any manual `_tags_` edits.

**Comment by aantron** [comment]
Cool, thanks.
