### ISSUE TITLE
Lwt_preemptive should provide an "at_exit" for use when a thread ends

### ISSUE THREAD

**Issue by hcarty** [ocsigen/lwt#251]
I'm working on bindings for [libyara](https://github.com/plusvic/yara) which requires a cleanup call when a thread which used the library exits.  It would be nice to have a way to provide init/cleanup functions which would be applied to each new/exiting thread.

**Comment by aantron** [comment]
Agreed in principle. I have zero experience with `Lwt_preemptive`, but, just glancing at it, couldn't you achieve this with some variation on

```ocaml
Lwt_preemptive.detach f (init (); v) >|= fun r -> cleanup (); r
```

Let me know what I am missing. If this turns out to be a documentation issue, we should fix that too.

**Comment by hcarty** [comment]
The cleanup, in this case, needs to be called once the preemptive thread exits, not the Lwt thread.  So the `at_exit` function would need to be called when the preemptive thread ends which may be after calls to `Lwt_preemptive.detach`.

**Comment by aantron** [comment]
I just looked at `Lwt_preemptive` more closely, and I see what you mean. PRs welcome; else I will reach this "eventually."

**Comment by hcarty** [comment]
I'm working on something - I'll hopefully be able to get an initial PR out for review soon.

**Comment by hcarty** [comment]
See #252

**Comment by aantron** [comment]
Closing as discussion was continued in #252.
