### ISSUE TITLE
'>>' fails if the next line ends in ';'

### ISSUE THREAD

**Issue by hcarty** [ocsigen/lwt#26]
Using `lwt.syntax`, the following fails:

    lwt () = let i = ref 0 in Lwt_io.printlf "Hello %d" !i >> incr i; Lwt_io.printlf "Hello %d" !i

The error is (with `incr i` as the offending piece):

    Error: This expression has type unit but an expression was expected of type 'a Lwt.t

**Comment by hcarty** [comment]
This issue is present with the ppx syntax as well.

**Comment by Drup** [comment]
I'm not sure we can do much about it without introducing brittle complexity in the syntax extensions. We can't change the respective priority of `>>`, `fun` and `;`, so we would need to basically inspect the AST and reorder nodes. It's a bad idea, since we don't have access to parens.

**Comment by aantron** [comment]
@hcarty I propose only adding a note to the documentation – see above commit. It doesn't seem like there is an alternative to `>>` either, since `;` is the [infix operator with the lowest precedence](http://caml.inria.fr/pub/docs/manual-ocaml/expr.html).

**Comment by hcarty** [comment]
@aantron That seems reasonable, thank you!
