### ISSUE TITLE
broken documentation page

### ISSUE THREAD

**Issue by jrochel** [ocsigen/lwt#268]
https://ocsigen.org/lwt/api/Ppx_lwt yields:

> Error
> Ocaml_lexer.Error(_, _)
> Ocisgen running in debug mode

**Comment by vasilisp** [comment]
Trouble with the ocsigen.org infrastructure. Until we fix it, you can look at:

https://ocsigen.org/lwt/2.5.1/api/Ppx_lwt (differs only slightly)
https://github.com/ocsigen/lwt/blob/master/ppx/ppx_lwt.mli

**Comment by Drup** [comment]
(Actually, I think it's an issue with wrong markup in the file)

**Comment by aantron** [comment]
Thanks. This is a duplicate of #263, though by different URL.
