### ISSUE TITLE
Drop support for 4.01

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#272]
The main reason is to be able to use `[@@ocaml.deprecated]` to communicate API changes before/after some future major release. There are several other breaking changes that would benefit from this.

It's also a prerequisite for eventually removing the Camlp4 extension.

Please voice any objections.

**Comment by rgrinberg** [comment]
0 objections from me.

But Is there a way to check out which opam packages still use the obsolete camlp4 extension? Would be better to still warn people about this. Since the camlp4 removal itself will be without a deprecation cycle

**Comment by aantron** [comment]
I have a script on my machine that downloads all transitive dependencies of Lwt found in OPAM, which I then look through (usually `grep`) for things like this. So, yes, I will warn at least the maintainers of those packages.

I will also mark `lwt.syntax` and the Camlp4 module as deprecated for a while, though I don't think I can get an automatic warning for this like for "normal" Lwt code. Haven't tried it yet.
