### ISSUE TITLE
no fdatasync prototype on OS X

### ISSUE THREAD

**Issue by yallop** [ocsigen/lwt#285]
`fdatasync` is apparently available as a system call in OS X, but there's no prototype for it in `unistd.h`.  

The `configure` test (which only checks that a program using `fdatasync` can be linked) succeeds, but compiling the source reveals the problem:

```
src/unix/jobs-unix/lwt_unix_job_fdatasync.c:61:17: warning: implicit declaration of function 'fdatasync' is invalid in C99 [-Wimplicit-function-declaration]
  job->result = fdatasync(job->fd);
                ^
1 warning generated.
```

**Comment by aantron** [comment]
I found this some days ago as well: https://github.com/ocsigen/lwt/blob/master/src/unix/lwt_unix.ml#L696; https://github.com/ocsigen/lwt/commit/d3f7e66fa3167e04463dac2aa767e81603bc4f9b

I haven't tested if `fdatasync` actually works on OS X, and obviously using an undocumented system call is not the best style. However, it doesn't seem to have caused any actual problems yet. Do you think it should be removed?

**Comment by yallop** [comment]
If the `fdatasync` prototype were intended to be used on OS X then it'd be worth adding a prototype.  But I think the fact that there's no prototype in the first place indicates that it's not intended to be used.  So the best thing is to check during configuration whether it's exposed.  I'll open a PR to do that.

**Comment by aantron** [comment]
Thank you.
