### ISSUE TITLE
Documentation in Lwt_process

### ISSUE THREAD

**Issue by pveber** [ocsigen/lwt#29]
It would be nice to have a few words describing the meaning of the various kinds of redirections in `Lwt_process`. As I understand it ``Keep` means sharing stdX with the parent, ``Dev_null` and ``Close` are self-explanatory (but there may be subtleties worth mentioning). I have however no clear explanation of the difference between ``FD_move` and ``FD_copy`.

Also, when calling `Lwt_process.exec` with an ``FD_move` redirection, the file descriptor should be closed while it is not the case with ``FD_copy`. I think this is also worth mentionning.

This confusion is most probably a consequence of my own ignorance of Unix programming, but some more explanations would not hurt I think. Maybe pointers to relevant external documents is enough (like [the unix ocaml book](http://ocamlunix.forge.ocamlcore.org/pipes.html))?

**Comment by darioteixeira** [comment]
Seconded.  `Lwt_process` would benefit greatly from having some basic documentation.

**Comment by aantron** [comment]
Agreed.

The attached commit should address the narrow issue of `Lwt_process.redirection` docs. The broader issue of documenting `Lwt_process` is part of #248. I also noted to refer to the Unix book there.

From reading the code, I am concerned about the exact behavior of `` `FD_move`` and `` `FD_copy``, with respect to effectively closing `fd`, on Win32. I will have to look into it once building on MinGW. There may be a bug, or the documentation may have to be adjusted. Leaving this issue open until then.

**Comment by aantron** [comment]
Closing in favor of the [documentation project](https://github.com/ocsigen/lwt/projects/2).
