### ISSUE TITLE
Preventing the use of Lwt.with_value in detached threads

### ISSUE THREAD

**Issue by zoggy** [ocsigen/lwt#298]
Hello,

Yesterday I spent some time chasing a bug in my program. I use detached threads (with `Lwt_preemptive.detach`) and in a function called in such a detached thread, I created `Lwt.t` threads and embedded them in constructors. These threads are later waited for in the main (lwt) thread. 

Everything works fine, except that I used `Lwt.with_value` when creating these Lwt threads in the detached thread. Depending on whether these Lwt threads had to wait or not, the behaviour changed, because of (I guess) `Lwt.current_data` was concurrently accessed by both the lwt thread (thread id 0) and my detached thread (thread id > 0).

I shouldn't have done this and I resolved this problem by embedding in a `fun () -> ...` function the lwt threads created in the detached threads, so they were created and executed only in the lwt thread (thread id 0), but it could be great to prevent the usage of `Lwt.with_value` in detached threads, for example by testing `Thread.id (Thread.self())`, raising an exception if it is different than `0`.

**Comment by aantron** [comment]
Agreed in principle. Not sure how the specific check you suggested would interact with `Lwt_unix.with_async_switch`, so would have to think about it more carefully. PRs welcome, otherwise I will reach this eventually :)

**Comment by zoggy** [comment]
Another problem is that it would introduce a dependency on the thread library... Well, maybe a warning in the `Lwt.with_value` documentation would be enough.

**Comment by aantron** [comment]
Will definitely add the warning. Will also leave this issue open after that, as a reminder to see what else can be done in the future.

**Comment by aantron** [comment]
Closing, as

- The documentation of `with_value` [warns](https://github.com/ocsigen/lwt/blob/f34a4f91c26fdd679a992845f92f1565c07af9d4/src/core/lwt.mli#L1556-L1557) about using it from other threads.
- The entire `with_value` mechanism is [deprecated](https://github.com/ocsigen/lwt/blob/0ef3b515a3aeea435e55d9a17ad986aa2b8ebb04/src/core/lwt.mli#L1453-L1480) now.
- We have switched terminology from threads to promises. Hopefully that, and the more thorough new docs, will make it more difficult for new users to think that `with_value` can be used from other threads.
