### ISSUE TITLE
Render error.

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/lwt#303]
In the `Spawning process` section: http://ocsigen.org/lwt/dev/api/Lwt_process.
I think it's not from Lwt, but from wikidoc.

**Comment by aantron** [comment]
Thanks, this is indeed a problem between ocsigen.org and wikidoc. It's all over the place in the Lwt docs :/

Was reported here: https://github.com/ocsigen/ocsigen.org/issues/19
There's a proposed workaround here: https://github.com/ocsigen/wikidoc/pull/7

Closing this in favor of those issues.
