### ISSUE TITLE
Lwt_io, Printf and Format

### ISSUE THREAD

**Issue by Drup** [ocsigen/lwt#310]
There are two issues with `Lwt_io`:

- It needs unix. but the `printf` part should not.
- All the `printf` functions are basically broken. They rely on `Printf` instead of `Format`, which has become the standard in OCaml pretty printing, and they do not handle the `%a` very well.

My current idea is to:

- Split Lwt_io in two parts, one unix-independent (`Lwt_format` ?)
- Deprecate `Lwt_io.print*`
- Reimplement all the printing functions in term of formats. There are some concerns with blocking, but I have some ideas to solve them.

I think this process would respect #293 and allows us to improve the state of lwt-based printing.

**Comment by aantron** [comment]
I always had the impression that a lot of the functions in `Lwt_io` should be in a module that corresponds to the I/O functions of `Pervasives` and does not depend on `Lwt_unix` – not just the formatting functions.

**Comment by Drup** [comment]
@aantron maybe we should create new functions in `Lwt_unix` for the stuff that should be in `Lwt_io`, deprecate them, and move `Lwt_io` in `lwt` after the deprecation ?

**Comment by aantron** [comment]
Something to that effect. I am not sure if `Lwt_unix` is necessarily the right destination, but we can use a deprecation to warn about removal of functions from `Lwt_io`.

**Comment by hcarty** [comment]
@Drup `Lwt_fmt` maybe?  For the `Format`-focused code?

**Comment by Drup** [comment]
I was wondering if my idea would work, so here is an implementation: https://gist.github.com/Drup/2698c69fd70cf526ba3164b135177bcd

**Comment by aantron** [comment]
The biggest part of this was done by @Drup in #548.
