### ISSUE TITLE
Disable 4.01 build in Jenkins

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#318]
Whoever added the 4.03 build – thank you :)

If possible, can the 4.01 build be disabled completely? I currently have it short-circuited anyway: https://github.com/ocsigen/lwt/blob/master/.jenkins.sh#L1

Current Lwt does not support 4.01 or build on it (AFAIK).

**Comment by vasilisp** [comment]
4.01 is disabled now.

I also added a 4.04 build while at it. Let me know if you notice any problems.

**Comment by aantron** [comment]
@vasilisp Thanks, looks like it's working good.
