### ISSUE TITLE
un-deprecate `Lwt_result`

### ISSUE THREAD

**Issue by c-cube** [ocsigen/lwt#320]
I still don't really understand why the module was deprecated, but the more I use lwt the more I can't bear with exception-based error handling in it. I think a well-developped, convenient `Lwt_result` module is critical for good error handling. Can we use this issue to discuss the future of `Lwt_result` then?

**Comment by samoht** [comment]
I concur. This is a very useful module which does not have other counter part in the library ecosystem.

**Comment by aantron** [comment]
FWIW, I gave this a +1, but I have to delay making a positive decision on this due to time constraints. Any links for future reading, libraries that do this right (probably Async), in-depth discussion, etc., appreciated.

**Comment by agarwal** [comment]
Related modules from Async:
- [Deferred.Result](https://ocaml.janestreet.com/ocaml-core/latest/doc/async/Std/Deferred.mod/Result.mod/)
- [Deferred.Or_error.List](https://ocaml.janestreet.com/ocaml-core/latest/doc/async/Std/Deferred.mod/Or_error.mod/). For some reason there is no `Deferred.Result.List`, which could be easily provided and would be more general than `Deferred.Or_error.List`. In case you don't know: `'a Or_error.t = ('a, Error.t) Result.t`.

**Comment by c-cube** [comment]
For those interested, follow-up design issues in #324.

**Comment by aantron** [comment]
Thanks!

**Comment by tte** [comment]
@aantron Hello! So what is a replacement for `Lwt_result`? I was really excited to using this module instead of spaghetti-code checks w/ Lwt.Infix and Result monads. But I can't compile, run CI w/ `-warn-error` flag now. Why this (experimental) module is deprecated and what is a replacement for?

**Comment by aantron** [comment]
@tte this module is *not* deprecated or experimental since Lwt 2.7.1 (April). It is a supported part of Lwt.
