### ISSUE TITLE
Compilation against 4.05

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/lwt#321]
`Lwt_unix` doesn't compile against OCaml 4.05 (currently in beta). The reason is an additional constructor in `Unix.open_flag` (`O_KEEPEXEC`).

This brings up quite an ugly situation. The constructor aliases could be removed, but that would break a lot of code. Alternatively, some conditional compilation mechanism could be used (and that's not exactly elegant). And of course some of the current packages in OPAM need to be fixed (with separate `+4.05` versions?).

**Comment by mfp** [comment]
Unpleasant as it is, conditional compilation (with cppo, I'd add) is the de-facto standard way to cope with incompatibilities across OCaml versions (most often in ppx extensions). AFAICS no separate OPAM packages are required if we go that route, and no existing code (that wouldn't break on its own anyway with OCaml 4.05) should break.

**Comment by aantron** [comment]
Should be fixed now in `master` by #322, and will be released in the coming days to OPAM.
