### ISSUE TITLE
OSX 10.11 opam install lwt make build failed

### ISSUE THREAD

**Issue by fr0zenrain** [ocsigen/lwt#326]
+ /Users/root/.opam/system/bin/ocamlfind ocamlopt -linkpkg -g -linkpkg -package ppx_tools.metaquot -package compiler-libs.common -I src/ppx src/ppx/ppx_lwt_ex.cmx -o src/ppx/ppx_lwt_ex.native
 File "_none_", line 1:
Error: Files /Users/fr0zenrain/.opam/system/lib/ppx_tools/ppx_tools.cmxa
        and /usr/local/lib/ocaml/compiler-libs/ocamlcommon.cmxa
       make inconsistent assumptions over implementation Location
 Command exited with code 2.

**Comment by Drup** [comment]
You will need to provide more information about your setup (the complete build log, for a start, and the output of `opam config report`).

**Comment by mfp** [comment]
On Fri, Mar 10, 2017 at 05:13:36AM -0800, fr0zenrain wrote:
> + /Users/root/.opam/system/bin/ocamlfind ocamlopt -linkpkg -g -linkpkg 
    ==================

> # File "_none_", line 1:
> # Error: Files /Users/fr0zenrain/.opam/system/lib/ppx_tools/ppx_tools.cmxa
                 ========================
> #        and /usr/local/lib/ocaml/compiler-libs/ocamlcommon.cmxa
              =====================
> #        make inconsistent assumptions over implementation Location
> # Command exited with code 2.

This looks like an issue with the opam/OCaml setup, where you have different
environments mixed up. Another possible reason could be that the
"system-provided" compiler (installed via homebrew or similar I suppose?) has
changed after ppx_tools was installed.

You can try to reinstall ppx_tools before installing lwt with
   
     opam reinstall ppx_tools

Alternatively, create a new switch using a specific (non-system) OCaml
compiler to make sure that all the libs are compiled with the same compiler.
You can install all the packages you had in the previous switch quite easily,
see
http://opam.ocaml.org/doc/FAQ.html#CanIgetanewswitchwiththesamepackagesinstalled

-- 
Mauricio Fernández

**Comment by fr0zenrain** [comment]
@mfp follow your advice,i resolved.thanks for your help.

at first i install ocaml toolchains with port, and last i removed port installed instead of brew because some errors,now all of the installed package i use opam, only a little package download source build.
i don't notice why ppx_tools have a bad install.

**Comment by Drup** [comment]
Seem solved, closing. :)
