### ISSUE TITLE
4.02 Jenkins appears to be broken

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#330]
From e.g. https://ci.inria.fr/ocsigen/job/Lwt-4.02/219/console

```
[...]
[ERROR] The current switch (4.02.1) is an unknown compiler switch.
[...]
[ERROR] The compiler switch 4.02.1 is not installed.
[...]
```

@vasilisp any ideas? IMO, it's okay to just disable 4.02 Jenkins completely, as long as we are still building the Ocsigen docs *somewhere*, I guess.

**Comment by vasilisp** [comment]
I threw away the 4.02.1 switch thinking that it was no longer needed, but the Lwt 4.02 configuration was still pointing to it. It is fixed now.

The docs are currently built with 4.03, so we can get rid of 4.02 if it becomes a burden.

**Comment by aantron** [comment]
Thanks!

**Comment by aantron** [comment]
I noticed that the Lwt docs on `ocsigen.org-data` haven't been committed since 18 February. Is the process maybe broken?

**Comment by vasilisp** [comment]
There were a couple of failures today. An infrastructure glitch (non Lwt-specific) that I think I understand. I will look into it tomorrow.

Were there any API (and thus doc) changes between 18 February and today? If not, the process finds nothing new to commit.

**Comment by aantron** [comment]
Ah, I don't think there were. Actually, #322 updates the API, but only on 4.05. It may make sense to move doc generation to a 4.05 build, once 4.05 is actually released.
