### ISSUE TITLE
Temporary file creation

### ISSUE THREAD

**Issue by copy** [ocsigen/lwt#336]
The following functions would be useful:

```ocaml
val open_temp_file : 
  ?buffer:Lwt_bytes.t ->
  ?perm:Unix.file_perm -> unit -> output channel Lwt.t

val with_temp_file : 
  ?buffer:Lwt_bytes.t ->
  ?perm:Unix.file_perm -> (output channel -> 'b Lwt.t) -> 'b Lwt.t
```

In particular, `with_temp_file` should safely delete the file when the callback returns or fails.
Inspired by [open_temp_file](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Filename.html#VALopen_temp_file) and [mkstemp](http://man7.org/linux/man-pages/man3/mkstemp.3.html).

**Comment by aantron** [comment]
Agreed in principle. I've written such Lwt helpers in my own projects as well.

**Comment by jsthomas** [comment]
I'm working on this issue.
