### ISSUE TITLE
Missing Lwt_unix implementation for potentially blocking Unix functions

### ISSUE THREAD

**Issue by mfp** [ocsigen/lwt#343]
It was found that `getcwd` can block and there's no `Lwt_unix` implementation (see https://github.com/ocsigen/lwt/issues/342). There might be more such `Unix` functions so it's necessary to look through `Unix` and identify other potentially blocking functions that would need a `Lwt_unix` (non-blocking) implementation. [Async's Unix_syscalls](https://github.com/janestreet/async_unix/blob/master/src/unix_syscalls.mli) can be used as a reference.

**Comment by aantron** [comment]
In addition, [libuv](http://docs.libuv.org/en/v1.x/) can provide a heuristic for what might block across more platforms, although some things might be bound in libuv to have a compatible interface, rather than because the underlying operation could block.

**Comment by aantron** [comment]
Other references:

- [glibc](https://sourceware.org/git/?p=glibc.git;a=tree) – Linux.
- [macOS Libc](https://opensource.apple.com/source/Libc/).

**Comment by aantron** [comment]
Closing this. We're more likely to use libuv for Lwt first (#328). In the meantime, we can handle missing functions on an as-needed basis.
