### ISSUE TITLE
opam files should be at the root.

### ISSUE THREAD

**Issue by Drup** [ocsigen/lwt#344]
Currently, I'm pretty sure lwt_ssl dev is impossible to pin properly. The opam files should be put at the root of the repository (named package.opam).

**Comment by aantron** [comment]
I guess `opam source --dev-repo --pin lwt_ssl` is not working, but you can pin by giving the path to the subdirectory if you run `opam source` and `opam pin add` separately.

**Comment by Drup** [comment]
@aantron You can't do `opam pin --dev lwt_ssl` either. In general, all the opam package follow the convention that opam files are at the top when they are in the repository. It's extremely weird to find them hidden in a subdir in `src/`.

**Comment by aantron** [comment]
Fair enough. I'll move them later; or PR welcome.

**Comment by aantron** [comment]
Reopening for now, as I don't have time to debug the CI until later.

**Comment by aantron** [comment]
Might be preempted by #374.

**Comment by aantron** [comment]
Apparently resolved by #374. OPAM files are now at the root, and `--dev-repo` pins seem to be working fine.
