### ISSUE TITLE
Transient test suite failure: Unix.EBADF on close

### ISSUE THREAD

**Issue by emillon** [ocsigen/lwt#350]
Hi,

From time to time the test suite fails with `Fatal error: exception Unix.Unix_error(Unix.EBADF, "close", "")`. I'm noticing it when building `pkcs11` on travis through [ocaml-ci-scripts](https://github.com/ocaml/ocaml-ci-scripts), which seems to run tests on dependencies as well.

Manually restarting it usually works, but this happens a lot (I'd say in 10% of builds)
so it should be easy to reproduce.

Here is the relevant build log excerpt:

```
#=== ERROR while installing lwt.3.0.0 =========================================#
# opam-version         1.2.2
# os                   linux
# command              make test
# path                 /home/opam/.opam/4.03.0/build/lwt.3.0.0
# compiler             4.03.0
# exit-code            2
# env-file             /home/opam/.opam/4.03.0/build/lwt.3.0.0/lwt-11742-736596.env
# stdout-file          /home/opam/.opam/4.03.0/build/lwt.3.0.0/lwt-11742-736596.out
# stderr-file          /home/opam/.opam/4.03.0/build/lwt.3.0.0/lwt-11742-736596.err
### stdout ###
# [...]
# rm -rf bisect*.out
# rm -rf _coverage/
# ./setup.exe -test 
# Running 110 tests for library "core".
Done. 0 test(s) skipped.
# Running 55 tests for library "unix".
(35/55) Running test "establish_server: order of exceptions" from suite "lwt_io"Running 1 tests for library "preemptive".
Done. 0 test(s) skipped.
# Running 19 tests for library "ppx".
Done. 0 test(s) skipped.
### stderr ###
# W: Cannot find source file matching module 'Lwt_unix' in library lwt-unix.
# W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
# W: Cannot find source file matching module 'Lwt_unix' in library lwt-unix.
# W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
# Fatal error: exception Unix.Unix_error(Unix.EBADF, "close", "")
# W: Test 'unix' fails: Command '/home/opam/.opam/4.03.0/build/lwt.3.0.0/_build/tests/unix/main.native' terminated with error code 2
# E: Failure("Tests had a 25.00% failure rate")
# make: *** [Makefile:42: test] Error 1
[lwt: ocamlfind remove] Command started
```

Thanks for maintaining `lwt`!

**Comment by aantron** [comment]
Yeah, this is the result of a [janky test helper](https://github.com/ocsigen/lwt/blob/master/tests/unix/test_lwt_io.ml#L63) I wrote, that makes assumptions about file descriptor numbers. It's annoying in Lwt's own CI, too.

I'll either remove it, or run it a loop, or think of a better way to do this. Any ideas are welcome.

**Comment by emillon** [comment]
Thanks for the quick reply.

I guess that the problem here that there is an additional fd allocation between the moment the fds are allocated and when the `with_client` parameter runs. Then it seems that the guessed FD is already closed, which causes the error.

If that's the case, it might be possible to try harder to detect the highest socket fd in the current process, for example by calling `readlink` on all files in `/proc/self/fd` and check which ones point to `socket:XXX`. But that is not very portable, and there still is an inherent race condition in this.

I think that this test is a bit too high level to be reliable. An alternative is to remove these tests and only test the interesting part in `with_connection` (that all these tests have in common):

```ocaml
Lwt.finalize
  (fun () -> f (ic, oc))
  (fun () -> close_if_not_closed ic <&> close_if_not_closed oc)
```

It would be necessary to extract and expose `close_channels : 'a channel -> 'b channel -> ('a channel -> 'b channel -> 'c) -> 'c` in `Lwt_io`, maybe hidden under `(**/**)`.

If that plan is OK with you I'm happy to provide a PR.

**Comment by aantron** [comment]
Thanks!

I think the second option makes the most sense; I vote in favor of putting it in `(**/**)`, and maybe we should give it some ugly name like `dbg_close_channels`, to leave the nice name available for potential other uses. Probably also comment by it to discourage use, in case someone reads the `.mli`.

The option with reading `/proc/self` seems like it could work, but only on Linux, so it wouldn't be portable enough for the Lwt test suite.

I'll be happy to review and merge such a PR – much appreciated :)
