### ISSUE TITLE
Point to discuss.ocaml.org from docs

### ISSUE THREAD

**Issue by mfp** [ocsigen/lwt#352]
[discuss.ocaml.org](https://discuss.ocaml.org) was just launched as an experimental service.

There's a bit of a (IMHO misguided) rush to create new categories (see e.g. the one for Core/Async), and I'm not going to suggest one be created for Lwt at this point in time. If discuss.ocaml.org goes somewhere it might happen at some point though -- after all Lwt is the most installed library as per OPAM (the 6 packages above it in the ranking are build tools or shims) and its ecosystem is huge.

I'm leaving this here as a reminder to keep an eye on discuss.ocaml.org and for future planning.
Depending on how it develops, Lwt's documentation could point to it.

**Comment by aantron** [comment]
We should probably join and help the experiment. Thanks for the heads up :)

**Comment by aantron** [comment]
Oh, and they turned on TLS, so the URL is now https://discuss.ocaml.org/. It doesn't seem to recognize at least a GitHub login if accessed through a non-https URL.

**Comment by aantron** [comment]
I think we should link to it, so I changed the issue title.
