### ISSUE TITLE
Lwt_unix.of_unix_file_descr should not eagerly call Unix.clear_nonblock

### ISSUE THREAD

**Issue by dsheets** [ocsigen/lwt#356]
If `~blocking` is supplied to `Lwt_unix.of_unix_file_descr`, `Unix.clear_nonblock` will be called outside of the lazy value of the `Lwt_unix.file_descr` `blocking` field. If `blocking` is never forced (e.g. because the fd is only used for metadata operations), the resulting `fcntl` syscall is unnecessary. Additionally, on some operating systems like macOS, calling `fcntl` `F_SETFL` on certain fd types (like symlinks opened with `O_SYMLINK`) is an error (`ENOTTY` in that OS's case for some reason). This can cause a change from `?blocking:None` to `?blocking:(Some true)` to suddenly produce errors when encapsulating these fds.

The relevant section of code seems to be
<https://github.com/ocsigen/lwt/blob/master/src/unix/lwt_unix.cppo.ml#L324-L342>.

I'd be happy to prepare a PR if you agree with my analysis.

**Comment by dsheets** [comment]
[fcntl_ln.tar.gz](https://github.com/ocsigen/lwt/files/1007938/fcntl_ln.tar.gz) is a reproduction of the surprising and relevant macOS behavior.

**Comment by aantron** [comment]
+1, thanks for finding this. A PR would be appreciated.
