### ISSUE TITLE
Factor out Lwt_sequence (doubly-linked list)

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#361]
[`Lwt_sequence`](https://ocsigen.org/lwt/3.0.0/api/Lwt_sequence) ([.mli](https://github.com/ocsigen/lwt/blob/6d1a16c4672c71abd7fc3d3f11e0739f2079e9cb/src/core/lwt_sequence.mli), [.ml](https://github.com/ocsigen/lwt/blob/6d1a16c4672c71abd7fc3d3f11e0739f2079e9cb/src/core/lwt_sequence.ml)) is pretty much an ordinary mutable doubly-linked list. As in the `Lwt_pqueue` issue (#360), it belongs in the standard library.

Unlike `Lwt_pqueue`, `Lwt_sequence` is actually referenced elsewhere in the Lwt API, in two places: [`Lwt.add_task_r`](https://ocsigen.org/lwt/3.0.0/api/Lwt#VALadd_task_r) and [`Lwt.add_task_l`](https://ocsigen.org/lwt/3.0.0/api/Lwt#VALadd_task_l). `Lwt_sequence` will therefore need to stick around, or become a bunch of aliases, even if the stdlib gets a linked list. 

Perhaps we should also start gradually deprecating these two functions. Their functionality can be implemented in terms of other Lwt functions, and they seem to be used in few places. I see them in use in:

- [fdopen/uwt](https://github.com/fdopen/uwt) in several places (OPAM package `uwt`)
- [nojb/ocaml-utp](https://github.com/nojb/ocaml-utp/blob/bbe647bf09faad438961a3a2cbeb4168be33f0ce/lib/utp_lwt.ml#L292) (OPAM package `utp`)
- [ocamllabs/ocamlot](https://github.com/ocamllabs/ocamlot/blob/1304889b97af994d0a9e4db7e9618e9a995ef138/lib/ocamlot.ml#L514)
- [ANSSI-FR/parsifal](https://github.com/ANSSI-FR/parsifal/blob/4dd5f7e93642c52c9a53005fe4e068af98d60f8f/lwt/lwt_semaphore.ml#L32)

**Comment by avsm** [comment]
ocamllabs/ocamlot is not in active use, so I've archived that repository

**Comment by aantron** [comment]
This seems good to me.

**Comment by aantron** [comment]
We can later add a link to lwt-dllist in the `Lwt_sequence` deprecation message.

**Comment by avsm** [comment]
Released Lwt_dllist as v1.0.0 at https://github.com/ocaml/opam-repository/pull/13262

Will start doing the trivial ports of existing uses of Lwt_sequence in Mirage to this.

**Comment by toolslive** [comment]
What's the plan for:
```
val exit_hooks : (unit -> unit Lwt.t) Lwt_sequence.t
```
?

I do need a way to deplete/process the exit hooks, but I honestly don't care about the data structure that contains them.

**Comment by aantron** [comment]
We need to add accessor-style functions for adding and removing hooks. Adding a hook will return an object of some abstract type, that can later be used to remove that hook.

We'll keep `exit_hooks` itself around in the API for long after we add these functions, however, so there should be no need to worry about this going away suddenly.

**Comment by toolslive** [comment]
No worries, but a deprecation warning usually means : "we now have a better way of doing this, and the API you're using will eventually go away.". Alas, here there is no alternative yet, so there's no way to clean up the warning.

**Comment by aantron** [comment]
Closing this until there is a doubly-linked list in the standard library, or in another library that is likely to be published to system package managers.

I originally wanted to make Lwt depend on [lwt-dllist](https://github.com/mirage/lwt-dllist), which is `Lwt_sequence` factored out of this repo. However, adding more little dependencies seems like a bad idea in light of this comment: https://github.com/ocaml/dune/issues/1847#issuecomment-518007209.

We already strongly discourage usage of `Lwt_sequence` with deprecation messages, and all exposed Lwt APIs that depend on it are also deprecated, and have alternatives. So, it is effectively an implementation detail.
