### ISSUE TITLE
Avoid grep in development build process

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#363]
From https://github.com/ocsigen/lwt/pull/354#issuecomment-302641989:

> Summary: grep 2.24 doesn't like the unicode chars in Jérémie's name, updating to grep 2.25 makes the problem go away.

I believe this only occurs if you are building a development version of Lwt (not an OPAM release). I believe the offending line is https://github.com/ocsigen/lwt/blob/cf5580b6362a05087227f6b889a3a6e6094baee8/Makefile#L20

This may be a vanishing problem, if grep 2.24 is "old enough," but maybe it's best to just avoid or work around this somehow.

This can probably easiest reproduced by installing grep 2.24 (from source?) in a Docker container, then installing OPAM, then running `opam source --dev-repo --pin lwt` in the same container.

Thanks to @domsj for tracking down this strange problem.

I labeled this medium, because of the need to install an old grep, potentially in a container.

**Comment by Drup** [comment]
I'm not even sure what this is for. It seems to be a handrolled version of the statically compiled oasis setup, which we should probably get rid of anyway. We could simply remove all that and use the oasis-generated makefile (with additional rules outside of the oasis section).

**Comment by aantron** [comment]
This may get pre-empted by #374.

**Comment by aantron** [comment]
This was resolved by the jbuilder port #374, which was merged earlier today. AFAIK, we don't use grep anymore in the Lwt build process.
