### ISSUE TITLE
Create a list of Lwt-related libraries, and link them from README

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#366]
An example of this is [lwt-parallel](https://github.com/ivg/parallel). Also, many libraries have `_lwt` packages. Let's collect the most relevant ones, and link to them from the README, so users can see "if I want to use Lwt and an have an HTTP server, I install..." Otherwise, we can try to get an "Lwt" section in [awesome-ocaml](https://github.com/rizo/awesome-ocaml), and link to that, or maybe someone can make an "awesome-lwt."

Post suggestions/discuss here.

cc @ivg

**Comment by c-cube** [comment]
I think awesome-ocaml has plenty of space for a lwt-related section. I'll add my own libs if this happens.

**Comment by aantron** [comment]
By the way, you can list all transitive dependencies of Lwt in OPAM by:

```
opam update
opam list --unavailable --depends-on=lwt --depopts --recursive --short
```

This will pull in some things that don't actually care about Lwt, like `cohttp` depends on Lwt optionally (for now), and anything that depends on `cohttp` at all will be listed, even if it doesn't use `cohttp` Lwt support.

**Comment by Drup** [comment]
I agree with @c-cube, this should be in awesome-ocaml instead.

Also, you want `--all`, not `--unavailable`. :)

**Comment by aantron** [comment]
@Drup:

```
       -A, --unavailable
           List all packages, even those which can't be installed on the
           system

       -a, --all
           List all the packages which can be installed on the system. This is
           the default when a query argument is supplied.
```

`--unavailable` seems more thorough.

**Comment by Drup** [comment]
Ah, yes. those options are better named in 2.0. :)
