### ISSUE TITLE
Update comments at the top of all code files

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#367]
The first three lines of `.mli` and `.ml` files in Lwt currently look like this ([example](https://github.com/ocsigen/lwt/blob/cf5580b6362a05087227f6b889a3a6e6094baee8/src/core/lwt.ml)):

```ocaml
(* Lightweight thread library for OCaml
 * http://www.ocsigen.org/lwt
 * (Module|Interface) Lwt
```

we want them to look like this ([example](https://github.com/ocsigen/lwt/blob/fdff5c09d47d2b020d4998ebed922acf383a2e9d/src/core/lwt.ml)):

```ocaml
(* OCaml promise library
 * http://www.ocsigen.org/lwt
```

- "Lightweight thread" terminology is deprecated. We especially want to avoid it in `.mli` files, since people read those – though most people probably don't care about the file headers.
- Repeating the module name (which is based on the file name) in the header is redundant and fragile.

The header for `src/core/lwt.ml` is already being changed in #354, but the rest need to be done.

**Comment by jsthomas** [comment]
I'll work on this issue.

**Comment by aantron** [comment]
Done in #376. Thanks @jsthomas!
