### ISSUE TITLE
Lwt_bytes.map_file signature

### ISSUE THREAD

**Issue by samoht** [ocsigen/lwt#37]
I am not sure to totally understand why `Lwt_bytes.map_file` doesn't take a `Lwt_unix.file_descr` as argument.

That API is not as easy to use as it should (see for instance https://github.com/samoht/ocaml-git/blob/master/lib/gitUnix.ml#L53)

**Comment by aantron** [comment]
Appears resolved. Feel free to comment/reopen if not.
