### ISSUE TITLE
Move Camlp4 syntax to a separate package

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#370]
To eliminate a depopt from `opam`, and as part of deprecating Camlp4. Related #338.

**Comment by aantron** [comment]
I tried doing something like #481 (factoring out the PPX) to Camlp4, but it doesn't seem to work. I think `archive(syntax ...) ...` predicates have to be directly in at least one package that is mentioned on the command line, not only findable through `requires` predicates. So, we can't use a "proxy" package, like for the PPX. This seems like a bug in Findlib, but I don't think we have time to wait for a fix.

I can think of two or three ways to solve this:

1. Just move the Camlp4 syntax out, without going through a proxy package phase. We would do this in 4.0.0, and cause breakage.
2. Duplicate the Camlp4 syntax both `lwt.syntax` and `lwt_camlp4`, until 4.0.0. This seems equally as easy/difficult as (1), but would be "softer." I don't know if there would be any difficulties I don't foresee, though.
3. Maybe it's possible to create a dummy library that has an `archive(syntax, ...)` predicate, and that will satisfy Findlib. I haven't tried it.

@Drup, any suggestions from your experience?

**Comment by Drup** [comment]
I think it's okay, in this case, to do a one time move. Does the camlp4 syntax extension still has many users ?

**Comment by aantron** [comment]
Yeah, I see `aws`, maybe `biocaml`, maybe `bitcoin`, `eliom`, `facebook-sdk`, maybe `hardcaml`, tests of `imaplet`, `iocaml`, `jitsu`, `joolog`, some examples in `js_of_ocaml`, `lambdoc` examples, `mongo`, `ojquery`, `ojwidgets`, `rdf`, `release`, `riak`, `themoviedb`, `usb`, `xe`, `xen-disk`, `xenctrl`, `xentropyd` just in opam. Didn't look into how many of those are presently maintained.

**Comment by aantron** [comment]
The linked commit duplicates Camlp4 in a `lwt_camlp4` package.

**Comment by aantron** [comment]
I should note that this approach results in Findlib warnings about duplicate interfaces in `lwt` and `lwt_camlp4`. These are temporary until 4.0.0.
