### ISSUE TITLE
Delete simple-top

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#371]
`simple-top` was deprecated in favor of [utop](https://github.com/diml/utop) in or before bb73e9834ceacb8e6c2aed7c8f19fdd81bc404af (summer 2011). There are no users in OPAM. A GitHub search for it returns only @bobzhang's [ocaml-book](https://github.com/bobzhang/ocaml-book) and @kkirstein's [proglang-playground](https://github.com/kkirstein/proglang-playground).

I think we can announce the removal of simple-top in the next minor release, and delete it 4.0.0.

Related #313.

**Comment by kkirstein** [comment]
That's fine with me, just kick it out as planned...
