### ISSUE TITLE
Create stress tests for Lwt

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#372]
We want to be able to subject various parts of Lwt to heavy load during testing. Ideally, we should be able to catch problems like https://github.com/ocsigen/lwt/issues/315, https://github.com/ocsigen/lwt/issues/315#issuecomment-301259032, https://github.com/ocsigen/lwt/issues/349, ~~assuming those are actually caused by Lwt~~ *these were caused by the [Skylake bug](https://lists.debian.org/debian-devel/2017/06/msg00308.html)*.

**Comment by aantron** [comment]
See also the [Stability project](https://github.com/ocsigen/lwt/projects/1).

**Comment by jsthomas** [comment]
I'm interested in working on this, but I would probably need need some suggestions about what specific parts of Lwt the load tests should stress.

I see that @copy mentions a relevant test [in the discussion here](https://github.com/ocsigen/lwt/issues/315), but there is a dependency on [uWebSockets](https://github.com/uNetworking/uWebSockets) for creating load. For this issue, should the tests be self-contained in OCaml?

**Comment by aantron** [comment]
Thanks for the interest!

I think the tests should be written in OCaml only, so that various OCaml developers don't have a hard time running them.

I'm not sure, actually, how we would proceed with this issue. Ideally, we would want to be able to reproduce some actual problems, in order to know that the stress tests themselves are valid and useful. I originally opened this before the Skylake bug diagnosis was announced. This is the only load-related issue I've heard of in Lwt.

So, if you have access to an affected machine, one way to proceed would be to write some test that can reliably trigger the fault within a few minutes.

However, given that it turned out to be a CPU bug, I'm not sure what the value of this would be to Lwt.

I suggest leaving this issue open for a while, in case somebody has ideas prompted by this recent commenting. Otherwise, I think we should close it, until some problem gives us direction.

Alternatively, maybe @copy, @domsj, and/or @smondet can give some advice on how to stress test Lwt – but again, it might be difficult, because in all cases something *else* was being stress-tested, that just happened to use Lwt.

**Comment by aantron** [comment]
Actually, I think one possibility is to look in Async, and also promise/future libraries for JavaScript, Java, or other languages, see if they have any stress tests, and try to port them. Hopefully, at least some of those tests are "good" in the sense of actually testing for potential problems. Then, we would implicitly benefit from experience of other teams.

Again, I'm not sure if this is a particularly efficient way to work, though.

**Comment by hcarty** [comment]
One potential use for stress-tests in general could be to illustrate performance and number-of-promises-and-sockets supported by different backends (select vs libev vs uwt vs jsoo vs ...).  Those numbers can be useful in general to track over time (looking for performance regressions) and finding weak points in each backend.

**Comment by aantron** [comment]
@hcarty in my experience with libev and select, the limit is entirely due to the implementation of the underlying API on each system, i.e. not due to Lwt. I believe Lwt supports *way* more concurrency than your typical system I/O API permits.

Of course, it would be nice to know immediately if we ever accidentally turn Lwt into the bottleneck. But I think in the vast majority of cases, we will effectively be testing something other than Lwt.

It may still be nice to have a general benchmark on that, though.

**Comment by hcarty** [comment]
Agreed on all points! Having those tests is useful though as, regardless of where the limit originates, users will just see Lwt as the thing that does well or poorly in a particular area.

**Comment by aantron** [comment]
I added the docs label because we should probably mention these limits, where they come from, and what to do about them.

**Comment by raphael-proust** [comment]
Maybe we could have an ipc-bench[0]-style benchmark where we collect this kind of limits for different systems. Basically we write a benchmark in a separate repo, it should collect result but also things like OS, processor type, version of Lwt and things like that. We tell people to run it and send us back results through some channel. Then we can aggregate the results and have a view of a range of machines.

[0]: http://www.cl.cam.ac.uk/research/srg/netos/projects/ipc-bench/

**Comment by aantron** [comment]
I will close this for now. It was originally motivated by what turned out to be the Skylake bug. Lwt itself seems pretty stable, so I don't think there is such an immediate apparent need for stress testing anymore.
