### ISSUE TITLE
Are Lwt.return_unit, etc., still necessary?

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#373]
`Lwt.return_unit`, `Lwt.return_false`, etc., are no-allocation versions of `Lwt.return ()`, `Lwt.return false`, etc. – but they require the user to perform the optimization manually. We would rather have the compiler perform the optimization automatically, or the optimization not be needed at all.

Current OCaml provides up to two ways to justify ~~eliminating~~ deprecating these functions:

- https://github.com/ocsigen/lwt/pull/94#issuecomment-59821934, which requires OCaml 4.03 (Lwt supports 4.02).
- Flambda, which requires study for whether it can do this optimization at all, and whether it is reliable. This issue is basically studying Flambda today.

In future OCaml, it *should* be possible to abuse modular implicits to "specialize" `Lwt.return` for some types.

Also, what is the purpose of `Lwt.return_some`, `Lwt.return_ok`, and `Lwt.return_error`? Those will always allocate.

**Comment by Drup** [comment]
Why not keep them ? It's not exactly high maintenance and avoid breaking compat.

**Comment by aantron** [comment]
I'm not proposing to remove them. If (once) they become unnecessary, I'd like to deprecate them, remove them from all examples, move them to the bottom of the `.mli` file, and otherwise discourage using them.

**Comment by aantron** [comment]
Sorry, I used the word eliminating :)

**Comment by hcarty** [comment]
@aantron I use `return_some`/`return_ok`/`return_error` to avoid parens/`@@`:
```ocaml
Lwt.return_some thing
```
vs
```ocaml
Lwt.return (Some thing)
(* or *)
Lwt.return @@ Some thing
```
I'm not sure if that's actually _better_.  But I do use them that way sometimes.

**Comment by aantron** [comment]
I'm reorganizing/documenting `lwt.mli`, and I just came back to this issue exactly because I want to deprecate `return_some`, `return_ok`, `return_error`. AFAICT, they don't serve any particularly useful purpose. Unlike the other functions, they perform no optimization. @hcarty @sagotch @zoggy @c-cube, what are your thoughts?

On syntax, I think I'd rather encourage `Lwt.return @@ Some thing`, or something else. IMO this isn't a serious enough syntax issue, for it to be worth solving in the interface of Lwt.

**Comment by hcarty** [comment]
I use them pretty often for the reason I mentioned above. If we keep `return_none` it makes sense to me to keep `return_some` for symmetry. If we keep those then I think it makes sense to keep `return_(ok/error)`.

A counter-argument to what I just said is that we have Lwt_result and can direct users to that. If we add Lwt_option we could do the same for returning optional values.

**Comment by sagotch** [comment]
About the syntax, `Lwt.return @@ Some x + y` won't work. `Lwt.return_some @@ x + y` will.

But I have no strong opinion about this since it does not provide any optimization. I still like it but I could live without.

**Comment by aantron** [comment]
I'm closing this issue, with the original topic of the no-argument `Lwt.return_*` functions in mind. Inspecting the assembly suggests that `Lwt.return ()`, etc., are not optimized automatically. I tested on 4.05 with both Lwt and a test program compiled with Flambda -O3. So, `Lwt.return_unit`, etc., remain worthwhile for now.
