### ISSUE TITLE
Fix CI builds for Lwt contributors

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#377]
Some contributors have set up CI testing in their own GH forks of the repo, e.g. in #367 and #347. It seems that their builds don't work until they add `sudo: required` to their `.travis.yml`, e.g. https://github.com/ocsigen/lwt/pull/376/commits/d198a2b04230a3b68722ec7b929fdc8eeddb69ea.

I am not sure why the main repo's builds are working without that line. Perhaps they are getting grandfathered in after some breaking change in Travis, which the Lwt build predates. I guess we should just add `sudo: required` to the main `.travis.yml`, and make sure everything is working.

This issue is basically about making that change, opening a PR against the main repo, and waiting to make sure the builds don't break. To avoid triggering the AppVeyor builds, one can add `[skip appveyor]` to the commit message.

I want to note for contributors, that it's okay to submit a PR to the main repo, and just use it for triggering CI builds while still developing the change – just add a note in the PR that it's not ready for review. However, we shouldn't annoy people who choose to set up their own CI builds for whatever reason.

EDIT: cc @jsthomas @domsj

**Comment by persianturtle** [comment]
I'll take care of this one.
