### ISSUE TITLE
In-comment TODO: eliminate type constraint

### ISSUE THREAD

**Issue by raphael-proust** [ocsigen/lwt#381]
In `core/lwt_stream.ml` in the function `get_exn_rec`, there is a comment including a `TODO`:

```
(* TODO: Eliminate the above type constraint once the Lwt_stream.result
   type is eliminated. *)
```

**Comment by aantron** [comment]
Thanks for catching and reporting that. That TODO became out of date. The `Lwt_stream.result` type will stay for now, so I rewrote the comment.
