### ISSUE TITLE
Deprecate >> in the PPX

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#387]
See [discussion](https://discuss.ocaml.org/t/operator-in-lwt/296/11).

We should probably have the PPX emit a warning each time `>>` is used.

cc @Richard-Degenne @dkim @Drup

**Comment by raphael-proust** [comment]
I'm giving that a shot. First draft is https://github.com/raphael-proust/lwt/commit/4048ec5feaeab3bbe92f7e4b64d816131d32fa76

Is there a standard way to emit warnings from ppxs? Currently it just uses `prerr_string` inline. I didn't find examples online.

**Comment by aantron** [comment]
Off the top of my head, I think you can insert `[@..@ocaml.ppwarning]` annotations: see https://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec247. I've never tried this.

There are also some warning functions in one of the modules in the compiler's `parsing` directory. However, the PPX's version of that is coming from compiler-libs, and linked into the PPX, so I think it will end up printing to `stderr` – just with the same formatting as the compiler would use. `ppwarning` sounds like the better option.

**Comment by Drup** [comment]
Yes, warning should be done by adding some `ocaml.ppwarning` annotations in the emited OCaml code, using `Ast_mapper.attribute_of_warning`. Don't ever print yourself, it will break formatting.
