### ISSUE TITLE
`make test` doesn't redo all it should

### ISSUE THREAD

**Issue by raphael-proust** [ocsigen/lwt#394]
When working on #342 I noticed that running `make test` would not always reflect the most recent source changes. I had to do `make clean`, `make` and `make test` instead.

I'll try to reproduce on the new `jbuilder` build system.

**Comment by raphael-proust** [comment]
I cannot observe any of the symptoms with jbuilder. Closing.

**Comment by aantron** [comment]
Thanks for reporting and checking it!
