### ISSUE TITLE
[trivial] Fix the name of a test suite

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#397]
[It should be `lwt_list`, not `lwt_util`](https://github.com/ocsigen/lwt/blob/3679d135c080551e936d21c2056829018fc429f0/tests/core/test_lwt_list.ml#L155). See [`CONTRIBUTING.md](https://github.com/ocsigen/lwt/blob/master/doc/CONTRIBUTING.md) for the development workflow.

**Comment by Richard-Degenne** [comment]
On it!

This is probably one the easiest things to get started with.
