### ISSUE TITLE
Jbuilder + lwt_ppx

### ISSUE THREAD

**Issue by bluddy** [ocsigen/lwt#401]
Is there a way to use lwt.ppx with jbuilder? If not, what's required?

**Comment by aantron** [comment]
Yes, but for now you have to pin `master`. IIRC:

```
opam pin add --dev-repo lwt
```

Here is an example `jbuild` for using the PPX:

```
(jbuild_version 1)

(executable
 ((name hello_world)
  (libraries (lwt.unix))
  (preprocess
   (pps (lwt.ppx)))))
```

We plan to publish the jbuilder-based Lwt in OPAM in the next release, [3.1.0, ETA mid-late July](https://github.com/ocsigen/lwt/milestone/8).

Let me know if you have any trouble.

**Comment by bluddy** [comment]
Looks like the master-based version is incompatible with Lambda-Soup, so I'll have to make do without ppx for now :(

**Comment by aantron** [comment]
Heya, I believe I already know what the error is (found by @andrewray). I've opened the [above linked issue](https://github.com/aantron/markup.ml/issues/18) in Markup.ml (dependency of Lambda Soup) for dealing with it. I'll try to get a release of Markup out today. It should become installable tomorrow, depending on what it is merged into OPAM.

**Comment by aantron** [comment]
:scream: I'm sorry to suggest pinning yet another package, but Markup.ml `master` should now fix compatibility of Lambda Soup with Lwt (see above commit). However, I'm also preparing a release right now, so maybe you won't have to :)

**Comment by bluddy** [comment]
Thanks very much!

**Comment by aantron** [comment]
Ok, https://github.com/ocaml/opam-repository/pull/9499. Thanks for giving me a kick to finally release it.

**Comment by aantron** [comment]
Alright, Markup.ml is in and downloadable. I'm closing this issue, but feel free to comment and/or reopen if there are any further problems on the Lwt side.
