### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by raphael-proust** [ocsigen/lwt#402]
With the HEAD at `ba4deb79166235cfe32d5515dd99adc56793274d` I get the following error when trying to build.

```
$ jbuild clean
$ jbuild build
    […]
    ocamlc src/unix/lwt_unix_jobs_generated.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/bnwr/.opam/system/lib/bytes -I /home/bnwr/.opam/system/lib/result -I /usr/lib/ocaml -I src/core -I src/logger -no-alias-deps -I src/unix -o src/unix/lwt_unix_jobs_generated.cmo -c -impl src/unix/lwt_unix_jobs_generated.ml)
File "src/unix/lwt_unix_jobs_generated.ml", line 1:
Error: I/O error: src/unix/lwt_unix_jobs_generated.ml: No such file or directory

Waiting for 1 job to finish.
$ jbuilder build
      ocamlc src/logger/lwt_log.cma
      ocamlc src/core/lwt.cma
    ocamlopt src/core/lwt_condition.{cmx,o}
      ocamlc src/ppx/ppx_lwt.{cmi,cmti}
      ocamlc src/unix/lwt_unix.{cmi,cmti}
   gen_stubs […]
    ocamldep src/unix/lwt_unix.depends.ocamldep-output
Internal error, please report upstream including the contents of _build/log.
Description: "Lwt_config" not found in map <dependency graph in _build/default/src/unix>
Backtrace:
Raised at file "src/import.ml", line 17, characters 43-65
Called from file "src/module_compilation.ml", line 44, characters 24-63
Called from file "src/build_system.ml", line 300, characters 18-35
Called from file "src/build_system.ml", line 276, characters 8-25
Called from file "src/build_system.ml", line 276, characters 8-25
Called from file "src/build_system.ml", line 276, characters 8-25
Called from file "src/build_system.ml", line 323, characters 17-47
Called from file "src/future.ml", line 88, characters 40-45
Called from file "src/future.ml", line 83, characters 65-70
Called from file "src/future.ml", line 37, characters 9-12

Waiting for 2 jobs to finish.
```

After that, all the build end with the same error and the same backtrace.

I'll also get in touch with the jbuilder team, it says to do so.

**Comment by raphael-proust** [comment]
This happens if lwt is pinned to my local development repository (`$HOME/code/lwt`).

The problem changes if I pin it to `--dev-repo` and then try to build locally. I instead get

```
Error: Unbound value Lwt_config._HAVE_GETCPU
Error: Unbound value Lwt_config._HAVE_LIBEV
```

It seems like jbuilder doesn't know where to find/build `Lwt_config`. (It can't find it if pinned locally, and it finds a mismatching one if pinned to `--dev-repo`.)

**Comment by aantron** [comment]
Interesting, thanks for report. I upgraded to `1.0+beta10`, but can't reproduce here. cc @andrewray just in case, and subscribed to the jbuilder issue.

**Comment by aantron** [comment]
What happens when you run `make`, or `make default-config` before `jbuilder build`?

Also, the paths might look a little suspicious. Can you check out the previous OASIS build system, and run `make clean distclean`, then switch back to a branch with jbuilder and try again?

**Comment by aantron** [comment]
(`git clean -ffd` after switching back to jbuilder too)

**Comment by raphael-proust** [comment]
```
$ make
      […]
      ocamlc src/unix/lwt_config.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/bnwr/.opam/system/lib/bytes -I /home/bnwr/.opam/system/lib/result -I /usr/lib/ocaml -I src/core -I src/logger -no-alias-deps -I src/unix -o src/unix/lwt_config.cmo -c -impl src/unix/lwt_config.ml)
File "src/unix/lwt_config.ml", line 1:
Error: I/O error: src/unix/lwt_config.ml: No such file or directory
make: *** [Makefile:17: build] Error 1
```

-------------------------------------------

After `make default-config` (which doesn't report any errors)

```
$ jbuilder build
      […]
      ocamlc src/unix/lwt_config.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/bnwr/.opam/system/lib/bytes -I /home/bnwr/.opam/system/lib/result -I /usr/lib/ocaml -I src/core -I src/logger -no-alias-deps -I src/unix -o src/unix/lwt_config.cmo -c -impl src/unix/lwt_config.ml)
File "src/unix/lwt_config.ml", line 1:
Error: I/O error: src/unix/lwt_config.ml: No such file or directory
      ocamlc src/unix/lwt_unix_jobs_generated.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/bnwr/.opam/system/lib/bytes -I /home/bnwr/.opam/system/lib/result -I /usr/lib/ocaml -I src/core -I src/logger -no-alias-deps -I src/unix -o src/unix/lwt_unix_jobs_generated.cmo -c -impl src/unix/lwt_unix_jobs_generated.ml)
File "src/unix/lwt_unix_jobs_generated.ml", line 1:
Error: I/O error: src/unix/lwt_unix_jobs_generated.ml: No such file or directory
```

------------------------------------------------

Going back in time, using `make distclean` then moving forward in time and `git clean -ffd` fixed the issue.

Thanks!

**Comment by andrewray** [comment]
If I understand correctly, you updated a previous, already configured, clone of lwt and this left some files behind which confused the new jbuild process.

A quick sanity check for some blacklisted files in the configure.ml script would seem in order.

**Comment by aantron** [comment]
@andrewray I believe that's right. I guess this is vanishing problem, and maybe nothing ought to be done. If anyone else runs into it, we can link to this issue.

**Comment by aantron** [comment]
OTOH if, even after the switchover, we find developers are frequently (enough) switching between OASIS and jbuilder build systems (highly unlikely), we can address this with a sanity check or warning of some sort.

**Comment by aantron** [comment]
Ultimately, it's up to you. I guess the sanity check could be as simple as testing for the existence of `setup-dev.exe`, or whatever those files are called. I guess that's not so much work.

**Comment by andrewray** [comment]
It seems super easy to add, and while not fixing the given problem, would at least point it out.  It would be great if we could include an instruction to remove the specific offending file, which I assume is in lwt/unix somewhere.

**Comment by aantron** [comment]
Yep. If you can reproduce the problem, and that's enough to fix it, then those can be the instructions.

We could also have the instructions tell people to check out the predecessor commit of the jbuilder port, run `make distclean`, and then return to their branch. It would require installing OASIS, though. That commit is 30c3fd86f9ddebc98e54276100a59c79436b174f.

**Comment by aantron** [comment]
(Presumably, a contributor that generated the old build files in the first place already has OASIS installed, though)

**Comment by andrewray** [comment]
I'll have a dig around and see if I can reproduce the issue and produce a simpler way to fix it.  Even if not, a configure warning at least suggests we care!

**Comment by aantron** [comment]
+1 about caring.
