### ISSUE TITLE
Running tests should not require package react

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#422]
Currently, if one does `make test` with package `react` not installed, the result is

```
jbuilder runtest
Error: External library "react" not found.
-> required by "src/react/jbuild (context default)"
Hint: try: jbuilder external-lib-deps --missing @runtest
make: *** [test] Error 1
```

I guess this is because we have tests for `lwt_react`, and the tests expect it to be present unconditionally.

What's the right way to make this conditional? `(optional)` in `test/react/jbuild` didn't work (nor did I expect it to), neither in the alias nor in the executable. The other alternative I can quickly think of is giving `lwt_react` its own testing system, which seems dubious.

@andrewray, @diml any suggestions?

**Comment by andrewray** [comment]
It should work with

```
jbuilder runtest --only-packages lwt
```

**Comment by aantron** [comment]
Thanks, that works. However, it still isn't quite right – the way the build system and testing are set up now, we *do* want to run `lwt_react` tests if `lwt_react` is being built. It's relatively easy using an `ocamlfind query` command in the `Makefile`, but I wonder if there is a better way using Jbuilder itself.

**Comment by aantron** [comment]
I suppose we could use the restricted command in `make test`, to match `make build`, and add another `make test-all` to match `make all`.

**Comment by andrewray** [comment]
I think you will have to do something conditional in the Makefile to test for lwt_react since it is a separate library.

Or use separate commands as above :)

PS I was never really happy with the `all` target.  If you add `test-all`, I think it should be renamed `build-all`

**Comment by aantron** [comment]
I went with the two targets, and renamed `all` to `build-all` as you suggested.

My overall impression of this is of some kind of tension between configuration/detection steps, multiple packages in one repo with different dependencies, depopts, and so on. Not sure we have the ultimate solution to this problem yet. However, most Lwt development is focused on package `lwt`, so it's good enough for now.

**Comment by diml** [comment]
I suppose that tests could be conditional indeed. @hhugo wants this as well for jsoo
