### ISSUE TITLE
Restore warnings as errors in CI

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#431]
Until the Jbuilder port (#374), we ran the OCaml compiler with all warnings as errors in CI. This was done by setting `LWT_WARNINGS_AS_ERRORS=yes` in [`.travis.yml`](https://github.com/ocsigen/lwt/blob/ccbb5020115e201f2bd8ddb568b2ba95c4acbb74/.travis.yml#L29) and [`appveyor.yml`](https://github.com/ocsigen/lwt/blob/ccbb5020115e201f2bd8ddb568b2ba95c4acbb74/appveyor.yml#L13), and using `myocamlbuild.ml` to check for this environment variable, and add `-warn-error +A` to compiler command lines.

Ideally, we would restore this behavior under Jbuilder.

**Comment by andrewray** [comment]
There is a `--dev` argument to jbuilder which I think is much the same thing.  The targets in the makefile (and any CI scripts) should probably use it.

**Comment by aantron** [comment]
Ok thanks, looking at it.
