### ISSUE TITLE
[easy] Delete Camlp4 from the manual introduction

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#449]
The Camlp4 syntax is deprecated, but we are still confusing users by [talking about it (at length) on the manual intro page (link; section "The syntax extension")](https://ocsigen.org/lwt/manual/). We should:

- Delete everything in the Camlp4 subsection of this.
- Either delete the Correspondence table for now, or adapt it to the PPX.
- Get rid of the Ppx subsection header – it's not necessary when there is no Camlp4.
- Get rid of the reference to "two" syntax extensions.

**Comment by bobbypriambodo** [comment]
Hi Anton, I'd love to take this on to learn more about the ppx syntax. Questions, though:

1) Do you wish to keep the ppx syntax documentation [separated](https://ocsigen.org/lwt/3.0.0/api/Ppx_lwt)? If so, I would think keeping the correspondence table doesn't make sense in the manual (perhaps move it to the ppx page?).
2) I suppose we should add a note about the deprecation of camlp4?

**Comment by aantron** [comment]
Thanks for looking at this.

1. I'm not sure yet. Ultimately, all the docs will get [rearranged](https://github.com/ocsigen/lwt/projects/2). However, we need good source material *somewhere*, and the table definitely seems worthwhile to have. I'd like to leave it up to you :)
2. The Camlp4 syntax is already [marked as deprecated](https://ocsigen.org/lwt/dev/api/Pa_lwt) on its own page, if that's what you mean (as opposed to Camlp4 itself). I think it's best to avoid mentioning it all elsewhere, to avoid drawing attention to it. I think we should act like it doesn't exist, but still retain its own docs for code that still uses it, and for readers that encounter code still using it.

**Comment by bobbypriambodo** [comment]
I see. Yes that's what I meant. I think that makes sense.

Okay then, let me see what I can come up with. 🙂
