### ISSUE TITLE
[easy] Document that Lwt_io.printf is more like sprintf than printf

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#455]
From https://discuss.ocaml.org/t/lwt-execution-order-and-parallelism/564/8:

`Lwt_io.printf` calls `ksprintf` internally. This has some surprising consequences:

- ~~`%!` doesn't really flush anything, since no channel is associated with a `ksprintf`.~~ *Addressed by @smithjessk in #544*.
- The [type is weird](https://ocsigen.org/lwt/dev/api/Lwt_io#VALprintf):

    ```ocaml
    val printf : ('a, unit, string, unit Lwt.t) Pervasives.format4 -> 'a
    ```

    Compare [`printf`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Printf.html#VALprintf) and [`sprintf`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Printf.html#VALsprintf):

    ```ocaml
    val printf : ('a, out_channel, unit) format -> 'a
    val sprintf : ('a, unit, string) format -> 'a
    ```

    It should look like `printf,` but it looks more like `sprintf`.

    I don't remember the details now, but I vaguely recall someone getting bitten, or at least nibbled, by this.

These are especially annoying, if one tries to refactor non-Lwt code to Lwt. The different semantics make that code transformation slightly dangerous. These things also came up when discussing #310 on IRC, but are not explicitly listed in that issue.

I don't know if this can/should be fixed somehow – it's probably a hard issue. But we should at least [document in the `.mli`](https://github.com/ocsigen/lwt/blob/540ac3d86db4c06d62793993c3372151a9ef221a/src/unix/lwt_io.mli#L363) file that `%!` does nothing, and you have to use `Lwt_io.(flush channel)` if you want to flush it. This part is relatively easy. It's also worthwhile to look at the other `printf`-style functions nearby, and see if they actually correspond to the ones in module `Printf` the way users expect, which `Lwt_io.printf` doesn't.

**Comment by aantron** [comment]
Also cc @Drup, due to considerable experience with `Format`, etc. :)

**Comment by Drup** [comment]
So, yes, this is pretty much what I meant in #310 (except, knowing Format/Printf too much, I didn't detailed the actual consequences of my various points).

I believe my alternative implementation posted in #310 solves most problems.

**Comment by aantron** [comment]
I haven't looked into `Format` enough. Are the resulting type signatures "close" enough to replace the ones now in `Lwt_io`, or this would be a breaking change if we were to use `Format` internally?

**Comment by smithjessk** [comment]
I'm interested in tackling this. Over the next 2-3 days, I'll make a PR that adds the documentation for `printf` (and `fprintf`, `eprintf`, if appropriate).

**Comment by smithjessk** [comment]
I took a stab at this with #544.

**Comment by aantron** [comment]
I think the important things here were done by @smithjessk in #544, so closing.
