### ISSUE TITLE
Timeouts and exceptions in subprocesses

### ISSUE THREAD

**Issue by theindigamer** [ocsigen/lwt#466]
Consider the following code
```
open Batteries

let foo =
  let cmd = ("", [|"cat";|]) in
  let timeout = 1.0 in
  let p = Lwt_process.open_process_in ~timeout cmd in
  let pout = Lwt_stream.to_string @@ Lwt_io.read_chars p#stdout in
  let%lwt output = pout in
  match%lwt p#status with
  | Unix.WSIGNALED _ ->
    let _ = print_endline "signaled!" in
    Lwt.return (Bad output)
  | _ ->
    let _ = print_endline "not signaled!" in
    Lwt.return (Ok output)

let _ =
  match Lwt_main.run foo with
  | Bad s -> Printf.printf "Bad %s\n" s
  | Ok s -> Printf.printf "Ok %s\n" s
```
compiled on lwt 3.1.0 and ocaml 4.03.0 using

```
ocamlfind opt -package lwt.unix -package lwt.ppx -package batteries -linkpkg -o foo foo.ml
```

This throws the exception:

```
Fatal error: exception Lwt_io.Channel_closed("input")
Raised at file "src/core/lwt.ml", line 2719, characters 24-25
Called from file "src/unix/lwt_main.ml", line 33, characters 8-18
```

If you replace the command with `[|"cat"; "foo.ml"|]`, then it works just fine, printing out the file itself.

If you don't care about the status and just try to read in information:

```
let _ =
  let cmd = ("", [|"cat";|]) in
  let timeout = 1.0 in
  Lwt_main.run @@ Lwt_process.pread ~timeout cmd
```

this also throws the same exception (again it works fine if the timeout isn't triggered). I suppose this is at least a documentation bug as `pread`'s docs don't declare that it throws an exception.

How do I get around this :slightly_frowning_face:?

**Comment by aantron** [comment]
This seems the same as #153 (let's leave both open). "Correctly" fixing it might require some small API change, but, in the meantime, I'll also try to get a "suggested" workaround later today, when set up to code. I believe it will involve creating a function that reads from the input channel in a loop, and carefully handles this exception.

And, indeed, `Lwt_process` docs need major improvement, including on this.

**Comment by aantron** [comment]
@theindigamer Try this:

```ocaml
let read_from_process : string Lwt_stream.t -> string Lwt.t = fun stream ->
  let buffer = Buffer.create 4096 in
  try%lwt
    let%lwt () = Lwt_stream.iter (Buffer.add_string buffer) stream in
    Lwt.return (Buffer.contents buffer)
  with Lwt_io.Channel_closed _ ->
    Lwt.return (Buffer.contents buffer)


(* Usage *)
let () =
  let process_stdin, push_line =
    Lwt_stream.create () in

  let process_stdout =
    Lwt_process.pmap_lines ~timeout:1.0 ("", [|"cat"|]) process_stdin in

  push_line (Some "foo");
  push_line (Some "bar");

  let result = read_from_process process_stdout in

  assert (Lwt_main.run result = "foobar")
```

I used `pmap_lines` so I could send an unterminated line to `cat` and see that I still get it. The reading-only version is [`pread_lines`](https://ocsigen.org/lwt/dev/api/Lwt_process#VALpread_lines).
