### ISSUE TITLE
Compiler version check is not cross-compilation-friendly?

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#477]
Lwt has a configure-time compiler version check (to support passing the `-O3` option only on OCaml >= 4.03):

https://github.com/ocsigen/lwt/blob/20a51b6dbf2bfc009faf2db5afbdebadb8d8ee2d/src/util/configure.ml#L94-L109

Since this is testing the version of the compiler that is running the script, I suspect that it's not friendly to cross compilation. @whitequark, @fdopen do you have any advice on how to do this correctly for the compiler that will be used for the target environment?

**Comment by whitequark** [comment]
Run `ocamlfind ocamlopt -version` (with the right ocamlfind flags for the build-to-host cross-compiler), which returns a simple string like `4.05.0`. That takes care of everything.

**Comment by aantron** [comment]
Thanks for the quick response. What are the right ocamlfind flags/how does one get them? I read the help output and man pages of `ocamlfind ocamlc` and `ocamlfind`, and the only thing that seemed relevant was the the `-toolchain` option of `ocamlfind`. If this is what should be used, how does one typically get the correct toolchain name?

**Comment by whitequark** [comment]
It is provided by the cross-compilation environment. Just make it possible to specify it for the lwt build process. If you never build binaries for the build system (i.e. you never run the output of ocamlc/ocamlopt) then you do not need to do anything as the `OCAMLFIND_TOOLCHAIN` environment variable is sufficient.

**Comment by aantron** [comment]
Excellent, thank you for your expertise!

I'll leave this issue open until the above code is fixed, and we also check for not building any binaries for the build.

**Comment by aantron** [comment]
The version check was removed in 88c745745e27681958cd48ccebf9cd7e179be7bb.
