### ISSUE TITLE
Stop flattening the installation directory

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#482]
We are currently installing all the Lwt packages in a flat directory, as in pre-Jbuilder days. This is for backwards compatibility with a few users that are making assumptions about the directory structure, namely by compiling with flags for package `lwt`, when, in fact, using `lwt.unix`. When `lwt.unix` and `lwt` are in the same directory, the `-I` flag for `lwt` is good enough to find `lwt.unix`.

We should probably check one more time for packages depending on `lwt.unix`, or other `lwt` sub-libaries, incorrectly when releasing 3.2.0. We'll unflatten the directory in 4.0.0.

**Comment by Drup** [comment]
I think users that don't lookup in META files in 2017 deserves their build to be broken.

**Comment by aantron** [comment]
I would, if it were just that, but even users that look up `META` files can have this broken, because the `META` for `lwt` was good enough to compile against `lwt.unix` in a flat directory. I had this mistake in Markup.ml, for example, despite using `ocamlfind` "carefully," and there were a few other such projects found by @andrewray.
