### ISSUE TITLE
Remove the Unix stubs generator

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#523]
The [stubs generator](https://github.com/ocsigen/lwt/blob/caa642e8ecf043dae522bb7bedc90b1ca471c9e3/src/unix/stubs/gen_stubs.ml) (in [`src/unix/stubs`](https://github.com/ocsigen/lwt/tree/caa642e8ecf043dae522bb7bedc90b1ca471c9e3/src/unix/stubs)) generates [several of the C files](https://github.com/ocsigen/lwt/blob/caa642e8ecf043dae522bb7bedc90b1ca471c9e3/src/unix/jbuild#L51-L78) that make up the Unix binding, and one `.ml` file:

```
    lwt_unix_job_access.c
    lwt_unix_job_chdir.c
    lwt_unix_job_chmod.c
    lwt_unix_job_chown.c
    lwt_unix_job_chroot.c
    lwt_unix_job_close.c
    lwt_unix_job_fchmod.c
    lwt_unix_job_fchown.c
    lwt_unix_job_fdatasync.c
    lwt_unix_job_fsync.c
    lwt_unix_job_ftruncate.c
    lwt_unix_job_link.c
    lwt_unix_job_lseek.c
    lwt_unix_job_mkdir.c
    lwt_unix_job_mkfifo.c
    lwt_unix_job_rename.c
    lwt_unix_job_rmdir.c
    lwt_unix_job_symlink.c
    lwt_unix_job_tcdrain.c
    lwt_unix_job_tcflow.c
    lwt_unix_job_tcflush.c
    lwt_unix_job_tcsendbreak.c
    lwt_unix_job_truncate.c
    lwt_unix_job_unlink.c
    lwt_unix_jobs_generated.ml
```

It is meant to cut down on repetitive code. However, I personally have found it to be slightly opaque, and potentially doing more harm to legibility and maintainability than good.

This issue is about removing the stubs generator, and replacing it by ordinary code. Alternatively, if the stubs generator is really very useful, then this issue is about explaining why that is :)

Probably the easiest way to remove the stubs generator is to dump the code it generates, and commit it. It should be found in `_build/default/src/unix/jobs-unix`, and we want to move it from there to `src/unix/(unix|windows)_c`. After that, the `jobs-unix` directory can be deleted from the source tree.

I am not sure if the generator is making different code on Unix and Win32 platforms – I would assume so. In that case, to dump on Win32, a Windows machine may be needed, but the easiest way may be to echo the contents of the generated files into the build log in AppVeyor, and take them from there.

cc @cedlemo due to recent work on the Unix binding :)

**Comment by cedlemo** [comment]
@aantron, 

I would like to continue with this if you don't mind.

**Comment by aantron** [comment]
Of course I wouldn't mind, it would be very welcome again :)

**Comment by aantron** [comment]
By the way, you're welcome to rename the files as you see fit after dumping (if you go that route), for example to be consistent with the naming in PR #521.

**Comment by cedlemo** [comment]
I just saw that I make a little error when naming one file (it is a detail but it annoys me): 

```
unix_fstat_64_job.c
unix_lstat_64_job.c
unix_stat64_job.c
```

Is it ok if I rename it in the PR for this issue or would you like a different PR.

**Comment by aantron** [comment]
I think it's fine to rename it in the PR for this issue.

**Comment by cedlemo** [comment]
I have been able to modify the gen_stubs.ml like this: 

```
diff --git a/src/unix/stubs/gen_stubs.ml b/src/unix/stubs/gen_stubs.ml
index a8ae736..c8b612a 100644
--- a/src/unix/stubs/gen_stubs.ml
+++ b/src/unix/stubs/gen_stubs.ml
@@ -730,7 +730,7 @@ module GenFake = struct
 end
 
 let gen job =
-  let fname = "lwt_unix_job_" ^ job.name ^ ".c" in
+  let fname = "unix_" ^ job.name ^ "_job.c" in
   let oc = open_out fname in
   let job64 = {
     job with
```

and compile it with :

 `ocamlc -w +A-4-29 -o gen_stubs.exe gen_stubs.ml`

so that it generates the files with the same pattern for their names as we did in the unix_c/ directory.

I should be able to add a generic header with copyright if needed (could you give me a hint on where I could find one for those files ?). 

Furthermore, the C files use the check based on the `LWT_ON_WINDOWS` macro in order to compile or not the code.

Would you like to keep the gen_stubs.ml generator or not (modified or not) ?

**Comment by aantron** [comment]
> Would you like to keep the gen_stubs.ml generator or not (modified or not) ?

I'd rather not have the generator, unless there is some major advantage to having it. Let me know if you find one.

> I should be able to add a generic header with copyright if needed (could you give me a hint on where I could find one for those files ?).

You should be able to take the one from `gen_stubs.ml` itself, and prepend it to each dumped file.

**Comment by cedlemo** [comment]
> You should be able to take the one from gen_stubs.ml itself, and prepend it to each dumped file.

It seems that I was not clear, I just run the modified generator and it generated the files I want with the good names:

```
ls *.c
unix_access_job.c  unix_chown_job.c   unix_fchmod_job.c     unix_fsync_job.c      unix_lseek_job.c   unix_rename_job.c   unix_tcdrain_job.c  unix_tcsendbreak_job.c
unix_chdir_job.c   unix_chroot_job.c  unix_fchown_job.c     unix_ftruncate_job.c  unix_mkdir_job.c   unix_rmdir_job.c    unix_tcflow_job.c   unix_truncate_job.c
unix_chmod_job.c   unix_close_job.c   unix_fdatasync_job.c  unix_link_job.c       unix_mkfifo_job.c  unix_symlink_job.c  unix_tcflush_job.c  unix_unlink_job.c
``` 

like the following : 

```c
/*
 * unix_access_job.c
 * -----------------
 *
 * File generated with gen_stubs.exe
 */

/* Note: this file was generated at configure time. If it does not
   work and you want to fix it, you can modify it and send the result
   to the ocsigen mailing list.

   If you are courageous you can also look at the ocaml script that
   generated this file (./gen_stubs.exe). */

/* Informations:

   - this is the expected prototype of the C function [access]:

       int access(char* path, int mode)

   - these are the expected ocaml externals for this job:

       external access_job : string -> Unix.access_permission list -> unit Lwt_unix.job = "lwt_unix_access_job"
       external access_sync : string -> Unix.access_permission list -> unit = "lwt_unix_access_sync"
*/

/* Caml headers. */
#define CAML_NAME_SPACE
#include <lwt_unix.h>
#include <caml/memory.h>
#include <caml/alloc.h>
#include <caml/fail.h>
#include <caml/signals.h>

#if !defined(LWT_ON_WINDOWS)

/* Specific headers. */
#include <errno.h>
#include <string.h>
#include <unistd.h>

/* +-----------------------------------------------------------------+
   | Converters                                                      |
   +-----------------------------------------------------------------+ */

/* Table mapping constructors of ocaml type Unix.access_permission to C values. */
static int access_permission_table[] = {
  /* Constructor R_OK. */
  R_OK,
  /* Constructor W_OK. */
  W_OK,
  /* Constructor X_OK. */
  X_OK,
  /* Constructor F_OK. */
  F_OK
};

/* Convert ocaml values of type Unix.access_permission to a C int. */
static int int_of_access_permissions(value list)
{
  int result = 0;
  while (Is_block(list)) {
    result |= access_permission_table[Int_val(Field(list, 0))];
    list = Field(list, 1);
  };
  return result;
}

/* +-----------------------------------------------------------------+
   | Asynchronous job                                                |
   +-----------------------------------------------------------------+ */

/* Structure holding informations for calling [access]. */
struct job_access {
  /* Informations used by lwt. It must be the first field of the structure. */
  struct lwt_unix_job job;
  /* This field store the result of the call. */
  int result;
  /* This field store the value of [errno] after the call. */
  int errno_copy;
  /* in parameter. */
  char* path;
  /* in parameter. */
  int mode;
  /* Buffer for string parameters. */
  char data[];
};

/* The function calling [access]. */
static void worker_access(struct job_access* job)
{
  /* Perform the blocking call. */
  job->result = access(job->path, job->mode);
  /* Save the value of errno. */
  job->errno_copy = errno;
}

/* The function building the caml result. */
static value result_access(struct job_access* job)
{
  /* Check for errors. */
  if (job->result < 0) {
    /* Save the value of errno so we can use it once the job has been freed. */
    int error = job->errno_copy;
    /* Copy the contents of job->path into a caml string. */
    value string_argument = caml_copy_string(job->path);
    /* Free the job structure. */
    lwt_unix_free_job(&job->job);
    /* Raise the error. */
    unix_error(error, "access", string_argument);
  }
  /* Free the job structure. */
  lwt_unix_free_job(&job->job);
  /* Return the result. */
  return Val_unit;
}

/* The stub creating the job structure. */
CAMLprim value lwt_unix_access_job(value path, value mode)
{
  /* Get the length of the path parameter. */
  mlsize_t len_path = caml_string_length(path) + 1;
  /* Allocate a new job. */
  struct job_access* job = lwt_unix_new_plus(struct job_access, len_path);
  /* Set the offset of the path parameter inside the job structure. */
  job->path = job->data;
  /* Copy the path parameter inside the job structure. */
  memcpy(job->path, String_val(path), len_path);
  /* Initializes function fields. */
  job->job.worker = (lwt_unix_job_worker)worker_access;
  job->job.result = (lwt_unix_job_result)result_access;
  /* Copy the mode parameter. */
  job->mode = int_of_access_permissions(mode);
  /* Wrap the structure into a caml value. */
  return lwt_unix_alloc_job(&job->job);
}

#else /* !defined(LWT_ON_WINDOWS) */

CAMLprim value lwt_unix_access_job(value Unit)
{
  lwt_unix_not_available("access");
  return Val_unit;
}

#endif /* !defined(LWT_ON_WINDOWS) */
```

As you can see, there is no copyright in them, should I have to add one, if yes which one?

**Comment by aantron** [comment]
Yes, I suggest that you put the generator's license header into these files for committing them.

**Comment by cedlemo** [comment]
sorry for the comment I deleted, it did not understand what you where trying to say me. My bad.

**Comment by aantron** [comment]
No worries :)
