### ISSUE TITLE
PPX: remove -no-debug option

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#528]
The `-no-debug` option disables PPX backtrace support (which is currently broken anyway).

In opam, `-no-debug` is used only by `sqlexpr`.

I've never heard of any complaints that backtrace support is too slow. On the contrary, everyone wants backtrace support to be restored and improved in Lwt.

I propose we make `-no-debug` do nothing, simplify the PPX code, and remove the option entirely in some far future version of Lwt.

**Comment by kandu** [comment]
`-no-debug` ease my life when hacking lwt.ppx, the generated code is mush shorter so that the generated parsetree is acceptable to be parsed by my own eyes. 😸
