### ISSUE TITLE
problems with ssl

### ISSUE THREAD

**Issue by toolslive** [ocsigen/lwt#530]
Ever since the release of `lwt.3.1.0`, [Arakoon](https://github.com/openvstorage/arakoon) had some failing 
ssl related tests.
```
(executing the simplest failing test)
arakoon$> python test_it.py server.quick.system_tests_ssl:TestTLS.test_inter_node_communication 
...
ERROR: test_inter_node_communication (server.quick.system_tests_ssl.TestTLS)

```

Since there's a version that works (3.0.0 and earlier) and a version that fails, we used `git bisect` to unearth where this problem was introduced.
It turned out to be commit [8bff603ae6d976e69698fa08e8ce08fe9615489d](https://github.com/ocsigen/lwt/commit/8bff603ae6d976e69698fa08e8ce08fe9615489d) .
Indeed, reversing just that commit on the tip of master, will make the test succeed.

Armed with the above information, @domsj took a look at the `lwt(_ssl)` source code, and  analysed:
The commit that broke it seems to delay calling `Unix.set_nonblock` until the lazy val is forced.
When using plain sockets the lazy val (the 'blocking' field of type `Lwt_unix.file_descr`) will be forced before any read/write is done on the socket.
However in `Lwt_ssl` this lazy val is never forced.
Hence the file descriptor is actually still in blocking mode (the default) when it calls e.g. `Ssl.read`.
This might result in `Ssl.read` blocking the ocaml thread. Which will result in mayhem for the arakoon test suite.

The reverse of linked commit will fix this. Another option is making sure `Unix.set_nonblock` is called early enough by forcing 'blocking' at the appropriate time from somewhere within `Lwt_ssl`. Probably adding `Lazy.force ch.blocking >>= function ...` in `Lwt_ssl.read/write` would be best, just like `Lwt_unix.read/write`.

**Comment by aantron** [comment]
@toolslive, I agree with the second approach. See if the attached commit fixes the test (and Lwt_ssl) behavior.

**Comment by aantron** [comment]
By the way, I want to factor `Lwt_ssl` out into its own new repo, like `Lwt_glib` in #524 (part of #511). Do you have any objections/thoughts on this?

**Comment by toolslive** [comment]
* Our ssl related tests agree with the patch. This whole anecdote does seem to point to missing tests. Wouldn't the first test where you set up an ssl based server and client where the client starts reading before the server send a message bump into this ?

* Factor out `Lwt_ssl` into its own repo: no objections, but wouldn't it make exposing the above problems a bit more involved?

**Comment by aantron** [comment]
Indeed, we need tests for `lwt_ssl`.

> Factor out `Lwt_ssl` into its own repo: no objections, but wouldn't it make exposing the above problems a bit more involved?

Assuming we add tests, it would delay when we find out about problems like this until the next time someone tries to develop `lwt_ssl` against Lwt `master`. Besides that delay, I think not.

**Comment by aantron** [comment]
On the other hand, with a factored-out Lwt_ssl, we could do a point release right now without polluting the Lwt release list, and just easily have a separate release schedule for Lwt_ssl :) That's not maybe as big a "pure-"technical deal as delays in finding out about breakage, but it does help to keep things organized. Compare the last point release of Lwt_ssl, 1.1.1, in the [Lwt releases list](https://github.com/ocsigen/lwt/releases).

Lwt_ssl just needs more maintenance, that would take care of its problems sufficiently no matter which repo it's in:

- In this repo, it would prevent it from being dead weight and an eyesore.
- In another repo, it would be enough to detect any bugs introduced by changes to Lwt in the months between Lwt releases.

The other repo has the advantage of being more organized on top of that.
