### ISSUE TITLE
lwt.unix can't be #required

### ISSUE THREAD

**Issue by emillon** [ocsigen/lwt#533]
Hi,

I'm trying to load `lwt.unix` in a toplevel and it fails because of an unknown module:

```
# #use "topfind";;
- : unit = ()
Findlib has been successfully loaded. Additional directives:
[...]
- : unit = ()
# #require "lwt.unix";;
/home/etienne/.opam/4.06.0/lib/ocaml/unix.cma: loaded
/home/etienne/.opam/4.06.0/lib/ocaml/bigarray.cma: loaded
/home/etienne/.opam/4.06.0/lib/bytes: added to search path
/home/etienne/.opam/4.06.0/lib/result: added to search path
/home/etienne/.opam/4.06.0/lib/result/result.cma: loaded
/home/etienne/.opam/4.06.0/lib/lwt: added to search path
/home/etienne/.opam/4.06.0/lib/lwt/lwt.cma: loaded
/home/etienne/.opam/4.06.0/lib/lwt/lwt_log.cma: loaded
/home/etienne/.opam/4.06.0/lib/lwt/lwt_unix.cma: loaded
# #require "lwt.unix";;
Error: Reference to undefined global `Mutex'
```

This worked with 3.1.0 and fails with 3.2.0. I've bisected it down to f6e0117685f575e9b765cff20005b56b14a29620.

Usually, this means that a library is missing in the `requires` field in `META`, but that does not look like it is the case, as `threads` (which seems to provide this module) is already a dependency.

Some notes:
- the problem does not happen with `utop`, but I guess that it is because it relies on threads itself
- I reproduced this on 4.05.0 and 4.06.0
- a quick way to reproduce it is `echo '#use "topfind";; #require "lwt.unix";;'|ocaml /dev/stdin`

Thanks!

**Comment by aantron** [comment]
Try doing `#thread;;` before `#require "lwt.unix";;`. This was indeed caused (or exposed) by the commit you found. It is related to https://gitlab.camlcity.org/gerd/lib-findlib/merge_requests/9, see also the link provided there by @dbuenzli: https://caml.inria.fr/mantis/view.php?id=7687.

**Comment by emillon** [comment]
Thanks for the quick answer. Adding `#thread;;` works, indeed.

I'm using that in a script to check that a library I'm building is "self-contained" (e.g. it detects when I add a dependency in `_tags` but forget about updating `requires` in `META`). If I understand the issue correctly, it is that the "thread" mechanism is something that applications should handle and not libraries.

Is there something that I could add to my `META` file to state that it will only work with "threads"? (and would cause the toplevel to make this `#thread;;` step implicit when loading my library)

Thanks!

**Comment by aantron** [comment]
Yeah, as I understand it, the way `-thread` is conceived now (and for the last 20 or so years) is that applications decide on it, and libraries have to either support both `-thread` and its absence (usually by being indifferent to it), or "require" it by failing at link-time if it's absent. They can't force it.

I'm not aware of anything you can add to `META` to force `#thread;;` or `-thread` to be passed when loading the library, unfortunately. I was looking for something like that when fixing the issue (https://github.com/ocaml/opam-repository/pull/11071#issuecomment-353131128) as well, but ended up doing the above-linked https://gitlab.camlcity.org/gerd/lib-findlib/merge_requests/9 as the next-best thing for batch-linked libraries (ordinary, non top-level usage).

**Comment by emillon** [comment]
OK, thanks! I guess this can be closed, then.
