### ISSUE TITLE
EINTR should not be automatically retried

### ISSUE THREAD

**Issue by rixed** [ocsigen/lwt#545]
This is rather common in unix to use EINTR like this:

1. register some signal handler to set some flag in case of some signal is received
2. start a long blocking syscall
3. if the syscall return -1 with errno to EINTR, check the flags
4. otherwise life goes on

Currently Lwt_unix.wrap_syscall prevent this pattern by silently restarting syscalls on EINTR.
Meaning working with signals and long running syscalls is much harder (one have to explicitely
cancel the clocking thread from the sighandler, I presume).

Would it be possible to not restart the syscalls on EINTR? Given only signals for which the user
installed explicitly a handlers will interrupt a syscall I guess it's not going to surprise users too much
if a read or a sleep fails with EINTR.
But maybe lwt uses some signals on its own and that's why EINTR is silenced?
If it's not possible, would it be then doable to have an `~on_interrupt` flag added to Lwt_unix blocking functions?

**Comment by rneswold** [comment]
I don't think I agree with this strategy. Supporting this feature would expose Unix-related behavior in the API. I like that LWT tries abstract the low-level details so that promises are, more or less, atomic. I thought LWT (and OCaml) allow you to reliably receive and handle signals without having to worry about EINTR in every, long-running promise. And when I say "handle signals", I mean do more than set a flag.

I think the programming model should be:

* register a signal handler
* run as many long-running promises as you need
* let the signal handler do what it needs when it gets its signal of interest -- even cancel threads
* don't worry about which promise was interrupted

**Comment by rixed** [comment]
OK, but when as a result from a signal you want to stop some threads unix makes this work automatically for you, while with lwt you have some bookkeeping to do.

**Comment by aantron** [comment]
@rixed, Lwt indeed uses some signals on its own, namely it catches SIGCHLD to implement `waitpid`. See comment here:

https://github.com/ocsigen/lwt/blob/c23bd6138e62651cd6f98394afd0bcdac161cc94/src/unix/lwt_unix.cppo.ml#L504-L508

and the handler here:

https://github.com/ocsigen/lwt/blob/c23bd6138e62651cd6f98394afd0bcdac161cc94/src/unix/lwt_unix.cppo.ml#L2181-L2198

I think this is necessary on Unix to have a non-blocking implementation of `waitpid`. Not suppressing `EINTR`, then, of course, will force users to have to wrap almost all I/O calls in restart loops, which seems burdensome.

I can't readily think of a way to both implement non-blocking `waitpid`, and still avoid restart loops. Any suggestions are welcome.

See also #494 about other `waitpid`/SIGCHLD problems. cc @gabelevi

**Comment by rixed** [comment]
For my use case it would be enough to not restart the blocking threads that have explicitly asked for it. For instance: `Lwt_unix.sleep ~restart_on_eintr:false 10.`.
In my mental model of Lwt where such a function result in an additional file descriptor in the main select loop, that would imply that when that select ends with EINTR Lwt would go through all the blocked threads and make runnable all those that have restart_on_eintr set to false, which seems fast enough. Then of course reality does not always follow my simple mental models :)

**Comment by aantron** [comment]
Perhaps we could add such a flag, but I would want to avoid potentially adding it to every API. Is this a problem specifically with `Lwt_unix.wrap_syscall`?

I read a bunch of base OCaml code. I noticed that in the specific case of `sleep`, OCaml's `Unix` also [loops on `EINTR`](https://github.com/ocaml/ocaml/blob/2602e423067c57115229f61d62d67069aee0df7e/otherlibs/unix/sleep.c#L41-L44). It doesn't restart most other calls, though.

Also, your mental model is fairly close, but you may find the introductory material [here](https://ocsigen.github.io/lwt/manual-draft/Lwt.html) useful :) In particular, `'a Lwt.t`s are promises, not threads, despite the old terminology that is still used throughout the (old) manual.

**Comment by rneswold** [comment]
> For my use case it would be enough to not restart the blocking threads that have explicitly asked for it. 

As @aantron noted, these really aren't threads. When you do a `read`, your promise isn't actually in the `read` system call. The associated handle is added to the set monitored by `select` (or `poll`, depending on which engine your application is using.) When there's data to read, the `read` call is made. This means the `EINTR` might interrupt the `select` call, not the `read` call so you'd have to cancel your read-promise anyways.

Or is my mental model incorrect?

**Comment by aantron** [comment]
@rneswold Yes, thank you for that clarification. In the general case, that is what happens.

I was assuming @rixed wants to run a long-running system call in the main thread for some reason, and still be able to interrupt it, but @rixed, what is your specific use case? This whole machinery for avoiding fully-blocking, long-running system calls is actually what Lwt already is on the inside.

**Comment by rneswold** [comment]
> By contrast, with Lwt I have to maintain a list of threads to cancel with all the sleeps and condwaits.

You could do something like this:

Pretend you have a function, `read s n`, which reads `n` bytes from the the socket `s`. Assume you also have a mutex, `m`, and condition variable, `cv`. Instead of simply calling `read`, all your workers can do this:

```
Lwt_condition.wait mutex:m cv <?> read s n
```

Your signal handler can then cancel all of them:

```
Lwt_condition.broadcast_exn cv Cancel
```

(If you want, you could even use the `Unix.EINTR` exception.) `broadcast_exn` will cause the `<?>` operator to return a `Fail` value.

**Comment by aantron** [comment]
@rneswold's suggestion is spot on (I think, if I understood the use case). To make it slightly neater, you would wrap `Lwt_unix.read` in your own `read`, that has a reference to this condition variable and performs the race/choose (`<?>`) operation internally.

The list you would have to maintain is now internalized in this condition variable.

I guess the only problem would be if you need this for many different I/O calls. It may become annoying to wrap them all, and ensure that you are always calling the wrapped versions.

**Comment by rixed** [comment]
@rneswold : Yes I was thinking about such a wrapper although I could not devise one that neat.

At the end of the day, this is not more bookkeeping than checking EINTR, therefore I'm closing this.
Thank you all!
