### ISSUE TITLE
Lwt.nchoose_split hangs indefinitely with an empty list

### ISSUE THREAD

**Issue by hcarty** [ocsigen/lwt#551]
The following will hang indefinitely:

```ocaml
let l : unit Lwt.t list = []

let _, _ = Lwt_main.run (Lwt.nchoose_split [])
```

Tested with Lwt 3.2.1 and Lwt's `master` branch as of b27bea7c4c57de0ff729fc07f6862852b573a45d.

Ideally `nchoose_split` would immediately return `[], []` or, at worst, fail.

**Comment by hcarty** [comment]
I see that this is expected from the test suite.  I would still propose changing the semantics here as I'm not sure a permanent sleep state is useful in this context.

**Comment by aantron** [comment]
Discussion took place in #552 and ended up in #557, so closing this. Thanks for reporting it.
