### ISSUE TITLE
Publish lwt_ppx 1.0.2

### ISSUE THREAD

**Issue by gabelevi** [ocsigen/lwt#558]
Would you mind publishing lwt_ppx 1.0.2 or something like that to opam? I'd love to be able to use the backtrace fixes 😁

**Comment by aantron** [comment]
Absolutely, I was planning to do it tomorrow, along with Lwt 3.2.2 :)

**Comment by gabelevi** [comment]
That would be awesome! Thanks a ton!

**Comment by gabelevi** [comment]
Lwt 3.3.0 & Lwt_ppx 1.1.0 include all the changes I need! Thanks again!
