### ISSUE TITLE
Lwt_io.file_length of a directory returns 0x7FFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by rixed** [ocsigen/lwt#563]
Not sure it is a bug at all, but I'd have expected an exception (Unix_error EISDIR or Failure) from that user friendly helper module.
What do you think

**Comment by aantron** [comment]
@rixed, that does sound like a bug. What system are you on?

I just tried on Ubuntu under WSL and got 512 for the length of a test directory, which is accurate, but probably about as useless as 0x7FFFFFFFFFFFFFFF.

**Comment by rixed** [comment]
That was on a Debian stretch, amd64, latest stable lwt (3.3.0)
