### ISSUE TITLE
waitpid EINTR issues

### ISSUE THREAD

**Issue by hannesm** [ocsigen/lwt#568]
I read a bit up on `waitpid`, and according to [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/functions/waitpid.html) (as well as Linux and FreeBSD man pages) it can return `EINTR`.  The code in `lwt_unix.cppo.ml` (for Unix platforms) is:
```OCaml
  Lwt.catch
    (fun () -> Lwt.return (Unix.waitpid flags pid))
    Lwt.fail
```

This means, upon receiving `EINTR` the Lwt task will fail.  Is this intended?  My intuition would be - as done for other system calls (`readable`/`writable`/`retry_syscall`) - that `EINTR` be handled by calling `waitpid` again.

I see some discussion earlier in #494 #545, but don't think this issue is addressed.  Please let me know what you think, and whether I'm misguided here.

**Comment by aantron** [comment]
@hannesm I believe that is the code of the [helper `_waitpid`](https://github.com/ocsigen/lwt/blob/d05d81b8784d3a995b4eeb4f137caa17e93a8fdf/src/unix/lwt_unix.cppo.ml#L2200-L2203), rather than `waitpid`. Looking at how the helper is called from `waitpid`:

https://github.com/ocsigen/lwt/blob/d05d81b8784d3a995b4eeb4f137caa17e93a8fdf/src/unix/lwt_unix.cppo.ml#L2210-L2214

...it seems `WNOHANG` will always be in the flags list. Presumably, the code is written with the assumption that `waitpid` with `WNOHANG` can't result in `EINTR`, which is what I would intuitively assume as well.

If the `WNOHANG` `waitpid` poll fails, Lwt seems to continue by monitoring `SIGCHLD`

**Comment by hannesm** [comment]
@aantron thanks for your explanation. 

> Presumably, the code is written with the assumption that `waitpid` with `WNOHANG` can't result in `EINTR`, which is what I would intuitively assume as well.

I don't have any intuition why `WNOHANG` should imply that the result can't be `EINTR`.

**Comment by aantron** [comment]
Avoiding a description of the intuition, this seems to be the case [at least on Linux](http://man7.org/linux/man-pages/man2/waitpid.2.html):

```
       EINTR  WNOHANG was not set and an unblocked signal or a SIGCHLD was
              caught; see signal(7).
```

POSIX and FreeBSD man pages don't seem to make such a guarantee, but nor do they actually say what interaction there is, if any, between `WNOHANG` and `EINTR`. I/we would probably need to see some other material, like a more thorough specification, or source code, to know what can happen.

**Comment by hannesm** [comment]
ah, ic.  I was following (as linked above) the POSIX spec (and FreeBSD man pages) ;)

in reality, I added some debug output and so far wasn't able to receive a EINTR on my FreeBSD systems (see https://github.com/hannesm/albatross/blob/e48d3b345701bfddc6674b3f6fd418f05400fbc7/src/vmm_lwt.ml#L15 for the code)

feel free to close this issue

**Comment by aantron** [comment]
Yeah, the combination of that hand-wavy intuition, and experience with POSIX blind spots, makes me suspect that `EINTR` was specified particularly to allow signals to interrupt a blocking `waitpid`, and either

1. the authors simply neglected to address `EINTR` on a polling `waitpid` completely, or
2. to avoid over-specifying, the authors left this open on purpose, but almost every implementation will make `EINTR` impossible on `WNOHANG`, same as Linux.

I vaguely suspect (1) is the more likely explanation, so I weakly prefer to not fix anything yet, until we are more sure there is a true problem :)

**Comment by aantron** [comment]
@hannesm Were you doing something like sending signals from another thread, to try to trigger `EINTR`?
