### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by Drup** [ocsigen/lwt#571]
According to [github's docs](https://help.github.com/articles/setting-guidelines-for-repository-contributors/):

> To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, docs, or .github folder. 

It's currently in the `doc/` directory (no *s*), and so is not visible when doing a github PR. We should move it.

Similar thing for the license file, it's not recognized by github automagical determination of licenses.

**Comment by aantron** [comment]
Thanks. I renamed `doc/` to `docs/`.

For the license, we have to wait for #560 about changing the license. GitHub doesn't recognize Lwt's existing license files (I tried some months ago).

**Comment by Drup** [comment]
Ah yes, I forgot about that. It's working now!
