### ISSUE TITLE
Deprecate the Lwt_unix.async_method machinery and eventually remove it

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#572]
Here is a description of it:

https://github.com/ocsigen/lwt/blob/0aa5063d55a303c8932ed619ecf3bbd5b0886669/src/unix/lwt_unix.cppo.mli#L68-L87

Of the three methods, `Async_switch`, AFAICT, was only ever working on Linux, but might be broken now (#184). Since it is non-portable, marked as experimental, probably broken, and unsupported, I think we should deprecate it and eventually remove it.

Of the remaining two methods, `Async_none` and `Async_detach`, `Async_detach` is the reason why someone would want to use Lwt at all, over `Unix`. In case we bind a system call that is not available in blocking form in `Unix`, we can expose both synchronous and asynchronous bindings from Lwt. So, we should also remove `Async_none`, and thus the whole `async_method` type.

IIRC, setting the async method explicitly is basically not used in opam. I would have to look again to see what the exact impact is.

**Comment by chambart** [comment]
I'm all for removing Async_switch. It was a neat trick, but is a too brittle to seriously consider keeping. But Async_none has its uses. There are not that many system call that are completely blocking for an unbounded time. Most of the things that doesn't have a usable non-blocking equivalent are disk IO, which are often fast enough not to care. In particular, if the disk cache has a good hit-rate, Async_none is faster than Async_detach. It matters when you are CPU bound rather than IO bound.
But the main reason for me to use it is that it is often far easier to debug with GDB with Async_none.

**Comment by aantron** [comment]
Thanks. I'll see about keeping `Async_none` somehow, maybe through a simpler API, or just the environment variable.

**Comment by chambart** [comment]
Thanks, I would be happy with only the environment variable

**Comment by aantron** [comment]
I looked in more detail, and I am now leaning towards making `Async_switch` be effectively a synonym for `Async_detach` in 5.0.0, and leaving `Async_none` working as now. I'll experiment with `Async_none` some more, and perhaps un-deprecate it. Once the code implementing `Async_switch` is gone, it should also be much clearer what to do next (probably nothing :)).

**Comment by adrianbrink** [comment]
What is the current status of `Async_none`?

**Comment by aantron** [comment]
It's unchanged from before this issue was opened.

**Comment by adrianbrink** [comment]
Does that mean that I can still use `Lwt_unix.async_method Async_none` even in 5.0.0?

**Comment by aantron** [comment]
That's what I'm leaning towards, as per the earlier comment. Can you say how or for what purpose you're using `Async_none`? Having this information will help if anyone ever considers removing it again later.

**Comment by aantron** [comment]
The attached commit makes `Async_switch` a synonym for `Async_detach`, and leaves `Async_none` working as before. It will be released in Lwt 5.0.0 in the coming days.
