### ISSUE TITLE
Doc links are all pointing to 404 error pages

### ISSUE THREAD

**Issue by shinzui** [ocsigen/lwt#576]
The README is pointing to 404 error pages, and the [manual](https://ocsigen.org/lwt/3.2.1/manual/manual) on oscigen is outdated.

**Comment by Drup** [comment]
Duplicate of https://github.com/ocsigen/ocsigen.org/issues/18 . The ocsigen.org website was renovated a few days ago. This should be fixed soon.

**Comment by aantron** [comment]
I believe this is fixed by @CelieArnaud in #579. At least, the links in the README and in the changelogs on the releases page seem to work.

**Comment by aantron** [comment]
Correction, the 404 part is fixed. We still need to have docs for current versions of Lwt generated.

**Comment by aantron** [comment]
The first result in Google (and Bing) searches for "Lwt API" points to https://ocsigen.org/lwt/api/, which is now dead (404). cc @balat @CelieArnaud

**Comment by aantron** [comment]
This has indeed been fixed.
