### ISSUE TITLE
Lwt examples: how to test with Alcotest

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#580]
Suggested by @bruce-ricard in Gitter (thank you).

I agree we should add this. The Lwt manual needs a rewrite, though, so instead of adding it immediately, I'm saving this as an issue for the future :)

**Comment by bobbypriambodo** [comment]
Should this be in Lwt docs instead of Alcotest docs? What is the reason of adding it here? (Not on Gitter, sorry.)

**Comment by aantron** [comment]
It could live in the Alcotest docs, and we could add a link to it.

I think Lwt will, or at least should, get its own example docs at some point. We can then include one about testing with Alcotest.

**Comment by aantron** [comment]
An [example](https://github.com/mirage/alcotest/blob/4c37892065cc829be10bcdd9a7249689f7a68b85/examples/lwt/test.ml) has been added to Alcotest in https://github.com/mirage/alcotest/pull/165 by @CraigFe (thanks!).
