### ISSUE TITLE
The "flags" parameter of Lwt_io.{open,with}_file is not well defined

### ISSUE THREAD

**Issue by kit-ty-kate** [ocsigen/lwt#587]
I wrote something like this in my code:
```
Lwt_io.with_file ~flags:[Unix.O_CREAT; Unix.O_EXCL] ~mode:Lwt_io.Output file f
```
but after some testing the behaviour I was expecting (i.e. flags being added to the default flags, I was expecting at least `O_WRONLY`) is not the one given by those function. Instead if this parameter is given it uses only those flags.

This behaviour is not documented on the functions (you have to read the code to know that), and apart from that I find this behaviour a bit weird (even more so that if you forget to add `O_NONBLOCK` the interest of Lwt disappears)

**Comment by aantron** [comment]
@kit-ty-kate thanks for the report. I tried to clarify the docs in the linked commit. Let me know if more is necessary.

Without `O_NONBLOCK`, Lwt is still useful. `O_NONBLOCK` is only supported on most Unix systems for Unix domain sockets and named pipes, and not for regular files. So, when `O_NONBLOCK` is not supplied or not supported, Lwt runs I/O operations in worker threads. This can be slower than `O_NONBLOCK`, depending on the usage pattern, but it preserves the cooperative programming model of Lwt. I added a note about `O_NONBLOCK` to the new docs.

**Comment by kit-ty-kate** [comment]
Thanks a lot for your explanation and your work !

I noticed a small mistake in this commit: you said `[0666]` when describing the default permission, when it should probably be `[0o666]`.

**Comment by aantron** [comment]
I used C/most other languages notation, in part because it's probably more familiar in the permissions context. But I'll switch it to OCaml syntax. On reflection, it probably will give people a useful clue about how to write octal in OCaml, helpful because octal is pretty rare.
