### ISSUE TITLE
match%lwt accepts all cases being exception cases

### ISSUE THREAD

**Issue by cyberhuman** [ocsigen/lwt#596]
According to https://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec264:
> It is an error if all cases are exception cases in a given pattern matching.

Checking in toplevel, the following does not compile, as expected:
```
# match () with exception exn -> ();;
Error: None of the patterns in this 'match' expression match values.
```

But `match%lwt` gives a run-time error instead:
```
# Lwt_main.run @@ match%lwt Lwt.return_unit with exception exn -> Lwt.return_unit;;
Exception: Match_failure ("//toplevel//", 1, 16).
```

**Comment by hcarty** [comment]
Good catch!

**Comment by raphael-proust** [comment]
I'll can give that a shot if no one has started yet…
