### ISSUE TITLE
Lwt_sequence implementation question wrt active nodes

### ISSUE THREAD

**Issue by Armael** [ocsigen/lwt#604]
This is not an issue per-se, but more a question I have regarding an implementation detail in `Lwt_sequence`.

In iteration functions (`iter_*`, `fold_*`), the code checks if the nodes are active before calling the function on them (e.g. [here](https://github.com/ocsigen/lwt/blob/master/src/core/lwt_sequence.ml#L128)).
However, unless I'm mistaking, it seems to me that nodes that are linked to the sentinel node are **necessarily** active (nodes can only have `active = false` after `remove` has been called on them, but then they have been unlinked). Is my understanding correct, or am I missing something?

If this reasoning is correct the check could be removed, which might even make the code slightly faster.

**Comment by aantron** [comment]
@Armael, this is out of my brain's cache ATM, but check out these discussions on the `active` field. They may help to answer your question:

- https://github.com/ocsigen/lwt/issues/405#issuecomment-308486923
- https://github.com/ocsigen/lwt/pull/542

If not, please ping here again, and I'll be happy to re-read the code, etc. :)

**Comment by Armael** [comment]
Thanks for the pointers!
I think the discussion and the code in #542 answers the question: #542 removes a check that used to be in `length` -- hence, by the same reasoning, the checks in `iter_*` and `fold_*` can be removed.

**Comment by Armael** [comment]
I'll submit a PR that does that, if you don't mind.

**Comment by Armael** [comment]
Actually, these checks are really needed, as illustrated by e.g. the `foldr with multiple removal` test: arbitrary nodes can be removed while iterating, including the current one. This means the current node can become inactive, and linked to an inactive node. To continue iterating, we then need to follow inactive nodes until arriving to actives nodes (or the end).

Sorry for the confusion!
