### ISSUE TITLE
Metrics support

### ISSUE THREAD

**Issue by hannesm** [ocsigen/lwt#610]
What I'd like to collect from lwt, similar to [`stat` of OCaml's GC module](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Gc.html#VALstat), is some statistics about Lwt tasks (number running, created, finished, waiting).  Is this possible at the moment (I failed to find an API for doing that)?
I've seen http://www.roscidus.com/blog/blog/2014/10/27/visualising-an-asynchronous-monad/ which is great for debugging, but requires a patched lwt version.

**Comment by aantron** [comment]
I don't believe there is such an API right now. We would, however, like to merge tracing (http://www.roscidus.com/blog/blog/2014/10/27/visualising-an-asynchronous-monad/) into the main Lwt repo (#180).

**Comment by aantron** [comment]
Closing in favor of #180 for now.
