### ISSUE TITLE
Clarify docs about `Lwt_throttle`

### ISSUE THREAD

**Issue by kohlivarun5** [ocsigen/lwt#620]
Looking at `Lwt_throttle`, the interface talks about the fields in seconds:

https://github.com/ocsigen/lwt/blob/master/src/unix/lwt_throttle.mli
```ocaml
val create : rate:int -> max:int -> n:int -> t
    (**
       @param rate maximum number of connections per second
       @param max maximum waiting time (in seconds)
       @param n initial size of the hash table
    *)
```

But the implementation makes me think it is not counting seconds or time but just the number:

https://github.com/ocsigen/lwt/blob/master/src/unix/lwt_throttle.ml
```ocaml
 type t = {
    rate : int;
    max : int; (* maximum number of waiting threads *)
    mutable waiting : int;
    table : elt MH.t;
    mutable cleaning : unit Lwt.t option;
  }
```

Want to clarify, is the `rate` limited and the `max` enforced by the number of outstanding/waiting or the time (in seconds) ?

**Comment by aantron** [comment]
It looks like `rate` is per second, and `max` is indeed the number of pending promises. I rewrote the docs in the attached commit, in part to clarify this. Please send PRs to add any more clarifications :)
