### ISSUE TITLE
Bad link to lwt manual in the description of the github repository

### ISSUE THREAD

**Issue by cedlemo** [ocsigen/lwt#623]
This is just a detail sorry, but the first link in the description header of the github repository point to a bad address:

```
OCaml promises and concurrent I/O. https://ocsigen.org/lwt/manual/
```
it should be (I guess).

```
OCaml promises and concurrent I/O. https://ocsigen.org/lwt/
```

**Comment by aantron** [comment]
Good catch, looks like the site structure changed. Updating the link.
