### ISSUE TITLE
Lwt_io.of_bytes + position don't work

### ISSUE THREAD

**Issue by NathanReb** [ocsigen/lwt#636]
I you run the following in utop:
```ocaml
let ichan = Lwt_io.of_bytes ~mode:Lwt_io.input (Lwt_bytes.of_string "abcd") in
Lwt_io.position ichan;;
```
you get:
```ocaml
- : int64 = -4L
```
which obviously is a bug as you can't `set_position` on a negative value.

I'm not familiar with `Lwt`'s internals but had a look and it appears `of_bytes` behaves inconsistently with the broader `make`.
[Here](https://github.com/ocsigen/lwt/blob/master/src/unix/lwt_io.ml#L525), in make, `max` depends on the mode while [here](https://github.com/ocsigen/lwt/blob/master/src/unix/lwt_io.ml#L555), in `of_bytes`, it doesn't.

I found it by writing tests for a function that is supposed to reset the position after processing the channel. I assume it should work on regular channels as if it wasn't, someone would probably have found out by now. Still I'll try it out and let you know.

I'm happy to submit a fix if this is indeed the issue here!

**Comment by aantron** [comment]
Confirmed. The code in `lwt_io.ml` is definitely wrong. Not sure which is the most "right" way to fix it yet, but any reasonable fix is welcome :)

**Comment by NathanReb** [comment]
Good! I'll give it a shot!
