### ISSUE TITLE
Should lwt really compile after an 'opam remove base-threads'?

### ISSUE THREAD

**Issue by UnixJunkie** [ocsigen/lwt#66]
Cf. https://github.com/ocaml/opam-repository/issues/2102

**Comment by aantron** [comment]
Solved in OPAM by https://github.com/ocaml/opam-repository/commit/878ed9da54d64c1131effe10e54a0d24ed30a5d4, see [note](https://github.com/ocaml/opam-repository/issues/2102#issuecomment-229238543) in https://github.com/ocaml/opam-repository/issues/2102.
