### ISSUE TITLE
Try using Alcotest

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#701]
Now that https://github.com/mirage/alcotest/issues/119 is solved by https://github.com/mirage/alcotest/pull/167 (thanks @CraigFe!), we should be able to use Alcotest for the test suite.

We probably can't use `alcotest-lwt` itself, because of dependencies during its installation. However, we can duplicate [this simple code](https://github.com/mirage/alcotest/blob/5176781845aee272a3d71a7dca50a24f828eda99/lwt/alcotest_lwt.ml#L17-L31) to make the asynchronous instance of Alcotest that we need for the Lwt tester.

EDIT: see also mirage/alcotest#177. If that is implemented, Lwt would benefit greatly from switching to Alcotest.

**Comment by CraigFe** [comment]
Cool; good to see Alcotest getting another user. Let us know if we can make any improvements on the Alcotest side :slightly_smiling_face: 

My next thoughts for an Lwt-related improvement would be https://github.com/mirage/alcotest/issues/166, which would likely allow backends to pass something like an `Lwt.catch` handler.

**Comment by aantron** [comment]
Thanks.

https://github.com/mirage/alcotest/issues/166 would indeed be nice.

In the long term, https://github.com/mirage/alcotest/issues/120 could be useful, in case we resurrect the Lwt BuckleScript/JS branch (https://github.com/aantron/lwt-branches/blob/js-promises/src/core/lwt.ml#L32).

**Comment by aantron** [comment]
Closing for now, in favor of watching the Alcotest repo.
