### ISSUE TITLE
Lwt 4.3 breaks compilation with musl

### ISSUE THREAD

**Issue by copy** [ocsigen/lwt#718]
To reproduce:

```
% opam switch create 4.09.0+musl+flambda
% cat test.ml
let () = Lwt_main.run (Lwt.return ())
% cat dune
(executable (name test) (libraries lwt lwt.unix))
% dune build test.exe
    ocamlopt test.exe (exit 2)
(cd _build/default && ~/.opam/4.09.0+musl+flambda/bin/ocamlopt.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -o test.exe -I ~/.opam/4.09.0+musl+flambda/lib/bytes -I ~/.opam/4.09.0+musl+flambda/lib/lwt -I ~/.opam/4.09.0+musl+flambda/lib/lwt/unix -I ~/.opam/4.09.0+musl+flambda/lib/mmap -I ~/.opam/4.09.0+musl+flambda/lib/ocaml/threads -I ~/.opam/4.09.0+musl+flambda/lib/ocplib-endian -I ~/.opam/4.09.0+musl+flambda/lib/result -I ~/.opam/4.09.0+musl+flambda/lib/seq ~/.opam/4.09.0+musl+flambda/lib/result/result.cmxa ~/.opam/4.09.0+musl+flambda/lib/lwt/lwt.cmxa ~/.opam/4.09.0+musl+flambda/lib/ocaml/unix.cmxa ~/.opam/4.09.0+musl+flambda/lib/ocaml/bigarray.cmxa ~/.opam/4.09.0+musl+flambda/lib/mmap/mmap.cmxa ~/.opam/4.09.0+musl+flambda/lib/ocplib-endian/bigstring.cmxa ~/.opam/4.09.0+musl+flambda/lib/ocaml/threads/threads.cmxa ~/.opam/4.09.0+musl+flambda/lib/lwt/unix/lwt_unix.cmxa .test.eobjs/native/test.cmx)
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libthreadsnat.a(st_stubs_n.o): in function `caml_thread_start':
st_stubs.c:(.text+0xab1): undefined reference to `sigsetjmp'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(startup_nat_n.o): in function `caml_startup_common':
~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/startup_nat.c:156: undefined reference to `sigsetjmp'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_secure_getenv':
~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:418: undefined reference to `issetugid'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_dlopen':~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:278: undefined reference to `dlopen'/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_dlclose':~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:284: undefined reference to `dlclose'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_dlsym':
~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:289: undefined reference to `dlsym'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:289: undefined reference to `dlsym'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_dlerror':~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:303: undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:Error: Error during linking
```

Looks like `lwt_unix.cmxa` adds `/usr/lib` to the search path:

```
% ocamlobjinfo ~/.opam/4.09.0+musl+flambda/lib/lwt/unix/lwt_unix.cmxa|grep object
Extra C object files: -llwt_unix_stubs -L/usr/lib -lpthread
```

In 4.2.1 it works fine:

```
% opam install lwt=4.2.1
The following actions will be performed:
⊘ removed   lwt.4.3.0
∗ installed lwt.4.2.1
Done.
% dune build test.exe
% ocamlobjinfo ~/.opam/4.09.0+musl+flambda/lib/lwt/unix/lwt_unix.cmxa|grep object
Extra C object files: -llwt_unix_stubs -lpthread 
```

This switch uses musl-gcc, which uses its own search path. It isn't compatible with objects from `/usr/lib` which were compiled with glibc. 

<hr>

Relatedly, when installing conf-libev, I need to pass `C_INCLUDE_PATH` and `LIBRARY_PATH` even though my compiler already has the right search paths baked in:

```
% cat test.c
#include <ev.h>
int main() {}
% musl-gcc test.c -lev
```

**Comment by aantron** [comment]
This is probably related to the new discover.ml (#699). Perhaps the new code is clean enough that you may be able to eyeball the problem...

https://github.com/ocsigen/lwt/blob/1f97720338b6cd65657f5c07ac0792fdf659d8fe/src/unix/config/discover.ml#L170-L178

The whole surrounding module is responsible for search paths.

**Comment by copy** [comment]
> This is probably related to the new discover.ml (#699). Perhaps the new code is clean enough that you may be able to eyeball the problem...

I'm no expert in these configuration scripts, but what would work best for musl-gcc is if the configure script first compiled the test code without `-L` or `-I` flags, only with `-llibrary`. The compiler then uses its own baked-in library and header paths and the entire configuration is controlled through the CC variable.

**Comment by aantron** [comment]
@copy, am I right in guessing that the `conf-libev` problem is a long-standing issue, that was present also before Lwt 4.3.x? Regardless, I will make a PR to fix that, too.

**Comment by aantron** [comment]
Where is `ev.h` installed on your system, or for musl-gcc?

I get:

```
$ musl-gcc test.c -lev
test.c:1:16: fatal error: ev.h: No such file or directory
compilation terminated.
```

This is under Ubuntu, with no libev installed specifically for musl-gcc to use, so it's what I'd expect.

**Comment by aantron** [comment]
I can't reproduce the `conf-libev` issue. I removed my system libev (prefix `/usr`) to be sure it can't be found, and built and installed a musl libev (``CC=musl-gcc ./configure --prefix=`pwd`/install``, checked output to be sure, and moved headers to `/usr/include/x86_64-linux-musl`, libraries to `/usr/lib/x86_64-linux-musl`). Then, in a clone of `opam-repository`, in `packages/conf-libev/conf-libev.4-11/files`:

```
$ opam switch 4.09.0+musl+flambda
$ eval `opam env`
$ ocaml discover.ml
testing for libev: ............................. available
$ opam switch 4.07.0+flambda
$ eval `opam env`
$ ocaml discover.ml
testing for libev: ............................. unavailable

      The following recquired C libraries are missing: libev.
Please install them and retry. If they are installed in a non-standard location, set the environment variables C_INCLUDE_PATH and LIBRARY_PATH accordingly and retry.

For example, if they are installed in /opt/local, you can type:

export C_INCLUDE_PATH=/opt/local/include
export LIBRARY_PATH=/opt/local/lib

To compile without libev support, use ./configure --disable-libev ...
```

`musl-gcc test.c -lev` also works, as does `opam install conf-libev`.

**Comment by copy** [comment]
> am I right in guessing that the conf-libev problem is a long-standing issue, that was present also before Lwt 4.3.x? Regardless, I will make a PR to fix that, too.

That's correct.

> I can't reproduce the conf-libev issue. I removed my system libev (prefix /usr) to be sure it can't be found

Right, in my case I do have a system libev (since I also use non-musl switches), which the current conf-libev discover script tries to compile with musl-gcc, fails and then gives up.

**Comment by aantron** [comment]
@copy, can you get `discover.ml` from [this gist](https://gist.github.com/aantron/bf68582c94bc681e23b6a1dd5e2b6379), run `ocaml discover.ml`, and tell me if it detects your musl libev correctly? It is my proposed fix to `conf-libev`. If you're curious, the actual diff is included at the bottom of the gist as `patch.diff`.

**Comment by copy** [comment]
@aantron Yes, this discover script detects my libev correctly, cheers!

**Comment by aantron** [comment]
Thanks!

The conf-libev patch is in https://github.com/ocaml/opam-repository/pull/14913, and I will release the Lwt changes in 4.3.1 shortly.
