### ISSUE TITLE
tests fail in getlogin

### ISSUE THREAD

**Issue by olafhering** [ocsigen/lwt#721]
Pull request #673 added three tests. But they fail in an automated, isolated environment. While there is a user `abuild`, the tests expect something that is not present:

````
[  150s] Test 'getlogin and Unix.getlogin' in suite 'lwt_unix' raised 'Unix.Unix_error(Unix.ENOENT, "getlogin", "")'
[  150s] Test 'getpwnam and Unix.getpwnam' in suite 'lwt_unix' raised 'Unix.Unix_error(Unix.ENOENT, "getlogin", "")'
[  150s] Test 'getpwuid and Unix.getpwuid' in suite 'lwt_unix' raised 'Unix.Unix_error(Unix.ENOENT, "getlogin", "")'
````

There are no error messages that give hints what might go wrong, also an strace does not give hints what might be missing.

This is with ocaml 4.05 in openSUSE Build Service.
[devel:languages:ocaml/ocaml-lwt](https://build.opensuse.org/package/show/devel:languages:ocaml/ocaml-lwt)

**Comment by aantron** [comment]
Thanks! These messages do tell what's wrong; the `getlogin` call in the tests resulted in `ENOENT`. These tests need to be skipped in some environments. We already had code for doing that; I just generalized it in `master` to skip the tests in more cases. See the linked commit, above.

Are you able to easily test Lwt `master` in your environment? Do you need a speedy 4.3.2 release?

**Comment by olafhering** [comment]
I could try `master`, but there is a cirular dependency.

`ounit` requires `lwt`; `lwd` requires `bisect_ppx`, `bisect_ppx` requires `ounit` (according to opam).

I will try to package `bisect_ppx` to be able to test this `master` branch.

**Comment by aantron** [comment]
Only `ounit-lwt` (a very recent new release) should require `lwt`. `bisect_ppx` does not require `ounit-lwt`. If this continues to be an issue, can you try `opam update`, and paste the exact error message?

**Comment by olafhering** [comment]
There is no opam in OBS. The `master` branch of `bisec_ppx` works for me, so I will test this `master` branch later today.

**Comment by aantron** [comment]
> The `master` branch does not fail the reported tests anymore. It fails with other tests, will open a separate issue for them.

Thanks, closing. Please report any other problems with Lwt you encounter :)
