### ISSUE TITLE
Unresonably low default listen backlog in Lwt_io.establish_server_generic

### ISSUE THREAD

**Issue by Lupus** [ocsigen/lwt#731]
From Lwt_io:

```ocaml
let establish_server_generic
    bind_function
    ?fd:preexisting_socket_for_listening
    ?(backlog = 5)
    listening_address
    connection_handler_callback =
(* ... *)
```

I've been debugging connection timeouts with my httpaf-based server when used as upstream for nginx, and turned out that I just needed to increase the listen backlog. I wonder if it makes sense to default to `SOMAXCONN` (if it's available on target platform) instead of magic number `5`? This seems to be popular behavior for Linux http servers.

**Comment by aantron** [comment]
Yes, we can do that. I'd be happy to accept a PR with changes resulting from your debugging. Another thing you may want to consider is using `accept_n` inside `establish_server_generic`. There is a commit to that effect [here](https://github.com/aantron/lwt-branches/commit/d5b429d5ce10674f5ca6a13ba7ba4cbd8b8130aa). That's from *my* time debugging httpaf/Lwt performance :)

**Comment by aantron** [comment]
It looks so far to me like `SOMAXCONN` should be on every platform that supports `listen` to begin with, so we might not need detection for it. It looks like it will be 128 on Linux. On Windows, it some value that will result in a backlog of around 200. Windows also has [`SOMAXCONN_HINT`](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-listen), which allows for larger values. However, we can just ignore that for now, until someone has a need for this (do you?).

**Comment by aantron** [comment]
I had checked the [POSIX man page](http://man7.org/linux/man-pages/man3/listen.3p.html) to be reasonably sure support should be widespread:

> Implementations shall support values of `backlog` up to `SOMAXCONN`, defined in `<sys/socket.h>`.

**Comment by Lupus** [comment]
I was unable to find SOMAXCONN in Unix module, so probably needs to be "re-exported" from a C stub? With some `#ifdef` Windows could also be supported, but I'm not personally interested in it :)

**Comment by aantron** [comment]
Since `SOMAXCONN` is defined on Windows, it's easier to just support it everywhere without any `#ifdef`.

**Comment by Lupus** [comment]
Oh, this should be trivial then. Do you still want a PR, or you've already dived into this yourself? :)

**Comment by aantron** [comment]
I will dive into it myself eventually, so the PR is optional, but if you want it done ASAP then a PR will be welcome :) I'm assuming it's not critical for your use, though, since you are probably already using some integer.

**Comment by Lupus** [comment]
Yeah, it's not critical for me, I have the following code right now as a workaround:

```
    let backlog =
      Stdio.In_channel.read_all("/proc/sys/net/core/somaxconn")
      |> String.strip
      |> Int.of_string;

    let%lwt server =
      Lwt_io.establish_server_with_client_socket(
        ~backlog,
        listening_address,
        connection_handler,
      );
```

I'm nearly out of space for yet another opam switch, so I'm inclined to wait for eventual fix in next releases :)
