### ISSUE TITLE
Is calling Lwt_io.shutdown_server within Lwt_main.at_exit safe?

### ISSUE THREAD

**Issue by Lupus** [ocsigen/lwt#744]
I'm trying to stop my tcp server using `Lwt_io.shutdown_server()` which gets called in `Lwt_main.at_exit()`, which in turn is called after `exit()` is called in my async exception hook.

Looks like the app just hangs at stopping the server. Is it related to deadlock, described in 12542945 (and #114)? What is the recommended way to stop the server? I at least want to ensure no further connections are established, as I'm tearing down some other resources in the app, so I don't want to respond to anyone at this point...

**Comment by aantron** [comment]
I would need a working small example to know if this is related to #114.

However, I'm concerned about what you're trying to do. The async exception hook is a last opportunity for debugging your program after it violates the assumptions of Lwt, such as writing to a log file. It shouldn't deliberately be used as part of any normal shutdown process. A call to the async exception hook indicates a programming error in your code (or in a library you may be using). The right way to stop the app is to deliberately code some kind of orderly shutdown process, and handle it explicitly. Note that the type of the async exception hook is `exn -> unit`, not `exn -> unit Lwt.t`. This is to suggest that it is not meant for running any more Lwt processes, neither explicitly, nor implicitly by triggering them with `at_exit`.

In general, I think it's best to avoid `at_exit` unless completely necessary, both the regular `at_exit` and `Lwt_main.at_exit`.

**Comment by aantron** [comment]
...and a call to the async exception hook indicates that the code needs an extra exception handler somewhere, if it is at all possible to insert it. That exception handler should trigger the orderly shutdown process, if that's the correct way to handle the exception in your application.

**Comment by aantron** [comment]
...and `exit` will happen only after the explicit, orderly shutdown. In other words, a call to `exit` shouldn't *mediate* the shutdown of the application.

**Comment by Lupus** [comment]
No-no, I'm not advocating for fancy shutdown with tons of async code involved in async exception hook! Exception means that something got badly broken and we better die, and let orchestration system restart us.

I just happened to define async exception hook to tune logging of exceptions to my taste (and calling `exit()` afterwards), and define at_exit handler with fancy shutdown so that It gets called after my signal handlers also call `exit()`. And now I'm enjoying the aftermath :joy: 

Probably I need to use a notification for propagating signal back into the promiseland, and avoid at_exit handler altogether.

You will be laughing, but I failed to find a way to do something akin to good old `abort()` from libc... There's only `exit()` which is quite high level, and calls my `at_exit` handler anyways.

**Comment by Lupus** [comment]
Is there any particular reason signal handlers registered with `Lwt_unix.on_signal()` do not support promises? I doubt they are being executed directly from OS signal handler, right?

**Comment by aantron** [comment]
IIRC they are not, they are executed as normal OCaml code on the normal stack. I think the reason they don't have promises in their type signature is because why would you want the signal "handler" (that is, the callback) to *wait* on a promise? You want it to resolve a promise, in other words it will want to call functions that look like `Lwt.wakeup_later`.

**Comment by aantron** [comment]
...and the overall `on_signal` having a final return value that is a promise would indicate a one-shot handler, but handlers can be triggered multiple times in general. So there's no part of the signature that `Lwt.t` should appear in, but the handler should probably either deal with resolvers (`Lwt.u`), or something equivalent to that, like the push function of an `Lwt_stream`, or any other way of sending a notification from the handler.

**Comment by Lupus** [comment]
Yeah, I just ended up coding notification, to find out that it's also not going to wait for promise to complete, and wrapped it up in `Lwt.async()`, which I could just do inside signal handler itself... Time to talk with my duck before I write even more weird code.

I also had an idea that I need some sort of mutex to ensure code in `Lwt.async()` runs only once, but looks like `wakeup_later` can solve it easier and more elegant. Thanks for your input, appreciated! :slightly_smiling_face:

**Comment by aantron** [comment]
Yes, the signal handler should call `wakeup_later` or some other function (another example is the push function of a React stream), to deliver the event into your application's normal processing flow, if at all possible. That may trigger normal shutdown according to the application's logic.

If the signal represents a true emergency, and you absolutely need to exit *now*, and have no time for delivering notification to the main logic, there is no time for a shutdown process anyway. This is all generally speaking, of course :)

I wouldn't expect even slightly complex programs to work well after `exit`, especially in response to a signal. For example, you might not be able to control the order of exit hooks. Even if I had to code something as simple as `cat`, and I went down this path, I would be sweating a lot :)

**Comment by Lupus** [comment]
Got it working with `wakeup_later`. It even treats second signal in a row as "die immediately" request (using `Lwt.is_sleeping`), and just exits discarding any shutdown process that might be running at that time. Sweet! :raised_hands: 

I believe this can be closed, as original issue was more of misuse of API/lack of common sense. Thank you for your time!

**Comment by aantron** [comment]
Great, glad it's working :)
