### ISSUE TITLE
writev needed on Windows for Httpaf

### ISSUE THREAD

**Issue by ulrikstrid** [ocsigen/lwt#745]
I'm trying to get Httpaf working on Windows and I now have it compiling but it fails at runtime with `Fatal error: exception Lwt_sys.Not_available("unix_writev")`.

In the docs it's stated that it probably could be implemented
> Not implemented on Windows. It should be possible to implement, upon request, for Windows sockets only.

What needs to happen to make this happen?

**Comment by aantron** [comment]
The easiest thing to do at first is to forward to regular `write` on Windows, and write only the first buffer. This is what Httpaf used to do on Unix as well, when using Lwt, before Unix `writev` was added.
