### ISSUE TITLE
lwt_unix linker flags cause linker warnings

### ISSUE THREAD

**Issue by oandrieu** [ocsigen/lwt#747]
The `unix_c_library_flags.sexp` flags as determined by `discover.exe` cause unseemly linker warnings on my system whenever I link in `lwt_unix` :
```
/usr/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
```

Indeed, `unix_c_library_flags.sexp`  is `("-lev" "-L/usr/lib" "-lpthread")`, but on Fedora/Redhats system `/usr/lib` contains 32-bits libraries whereas the system libraries directory is `/usr/lib64`.

**Comment by aantron** [comment]
Fixed by #748.
