### ISSUE TITLE
Provide non-eager / lazy Lwt.t

### ISSUE THREAD

**Issue by madroach** [ocsigen/lwt#749]
Hi,
to make an iterator like [Lwt_pipe.lwt_klist](https://github.com/c-cube/lwt-pipe/blob/master/src/Lwt_pipe.mli#L171) lazy and therefore stack-safe it would be nice to have an operation like ``Lwt.bind_lazy``, which would produce an ``Lwt.t``, that does not get resolved by the usual eager push-based callback mechanism, but only lazily on a pull-based request by a non-lazy operation.
I imagined that this could be easily implemented by adding another variant to the ``state`` GADT:
```ocaml
  type ('a, 'u, 'c) promise = {
    mutable state : ('a, 'u, 'c) state;
  }

  and (_, _, _) state =
    | Fulfilled : 'a                  -> ('a, underlying, resolved) state
    | Rejected  : exn                 -> ( _, underlying, resolved) state
    | Pending   : 'a callbacks        -> ('a, underlying, pending)  state
    | Proxy     : ('a, _, 'c) promise -> ('a, proxy,      'c)       state
    | Lazy      : (unit -> ('a, _, _) promise)
                                      -> ('a, underlying, inactive) state
```
As soon as someone wants to register a callback on a promise in ``Lazy`` state, the ``unit -> 'a promise`` function in the ``Lazy`` variant is called and the state of the resulting promise is used as the new state of the former lazy promise.
I tried to implement this, but got stuck due to difficulties in getting the various phantom types to work correctly.

I would now kindly ask for some feedback about the general idea of lazy promises. Do you find it unnecessary or useful?

**Comment by aantron** [comment]
Could this be achieved using the existing interface using `'a Lwt.t Lazy.t`?

You can make a simple prototype separately from Lwt.

I am skeptical of this, it seems like it will add a lot of complication. Also, I am not immediately aware of all the consequences of adding a lazy version of promises. We would need to refer to other work, such as papers or existing libraries, and their experience.

**Comment by madroach** [comment]
Yes, that is possible, but would obviously add some overhead.
Thanks for your feedback. Since you feel skeptical I won't pursue this any further.
