### ISSUE TITLE
Lwt_main.run throws on `exit(1)`

### ISSUE THREAD

**Issue by Schniz** [ocsigen/lwt#758]
The error it says is `Failure "Nested calls to Lwt_main.run are not allowed"`, which seems like a weird result.

I know that maybe `exit(1)` is not the "lwt"-ish way but maybe this error should say something else?

context: I got it as an issue in fnm: https://github.com/Schniz/fnm/issues/181
I fixed it with returning a `result`, instead of exiting, which is probably a better way of doing it.

**Comment by aantron** [comment]
Thanks, that was a bug in `Lwt_main`. The linked commit should fix it. I'll release this next Monday, mainly because there was a release this weekend, and I think I should limit the rate a little :)
