### ISSUE TITLE
Excessive memory consumption of `getservbyname`

### ISSUE THREAD

**Issue by jrochel** [ocsigen/lwt#762]
In my application as soon as `getservbyname` is called, memory consumption increases (immediately) by about 50 Mo. This effect does not stack.

My call chain is `pkg:cohttp-lwt-unix/Net.connect_uri` → `pkg:conduit/Resolver` `pkg:conduit-lwt-unix/Resolver_lwt_unix.system_service` → `Lwt_unix.getservbyname "http" "tcp"`.

I'm not sure how to proceed debugging this, so I'm hoping someone has an idea.

**Comment by jrochel** [comment]
In `pkg:conduit-lwt-unix/Resolver_lwt_unix.system_service` this what I used to pinpoint the abovementioned function:
```
print_endline __LOC__; Lwt_io.read_line Lwt_io.stdin >>= fun _ ->                  
Lwt_unix.getservbyname name "tcp" >≥ λ s →
print_endline __LOC__; Lwt_io.read_line Lwt_io.stdin >≥ λ _ →
```
Before the first keypress `top` shows a consumtion of ~373708 Ko, afterwards ~439244 Ko. This effect is reliably reproducible.

**Comment by jrochel** [comment]
I'm not so sure about my analysis above anymore.I fear it lacks precision and the leak could be somewhere else entirely. I'll close the issue for now and reopen it once I know more.

**Comment by aantron** [comment]
@jrochel, I'm looking at this right now.

> I'm not sure how to proceed debugging this, so I'm hoping someone has an idea.

I started with this program:

```ocaml
open Lwt.Infix

let () =
  Lwt_main.run begin
    prerr_endline "Starting...";
    Lwt_unix.sleep 5. >>= fun () ->
    prerr_endline "Calling getservbyname...";
    Lwt_unix.getservbyname "telnet" "tcp" >>= fun _ ->
    Lwt_unix.sleep 5. >>= fun () ->
    prerr_endline "Calling getservbyname again...";
    Lwt_unix.getservbyname "telnet" "tcp" >>= fun _ ->
    Lwt_unix.sleep 5.
  end
```

I see memory usage increase by about 70M at the first call to `getservbyname`. I just started looking at the implementation. I'm not sure why this would be characterized as a *leak*, though. It seems likely to be lazy initialization of some buffer.

**Comment by jrochel** [comment]
The memory seems to be liberated after a couple of minutes (3?) after a garbage collection. Forcing a garbage Garbage collection before that does not have any effect.

**Comment by aantron** [comment]
It may also be a stack for a worker thread, etc. I still haven't had time to look into it in detail. Is this causing a problem for a project?

**Comment by jrochel** [comment]
No real problem. It means that we need to allocate more memory on a docker container.
This is more a confounding factor in my investigations into a real memory leak that is causing real problems.

**Comment by jrochel** [comment]
The 70+something Mo seem to freed by the next occurrence of a full major GC.

**Comment by jrochel** [comment]
This is the leak(?) I have been hunting: https://github.com/mirage/ocaml-cohttp/issues/688

**Comment by aantron** [comment]
Closing this, as the issue was something other than Lwt. I didn't find time to find out exactly what is triggering that first allocation. We can return to it later, if needed.
