### ISSUE TITLE
test failure in simultaneous Lwt_timeout

### ISSUE THREAD

**Issue by olafhering** [ocsigen/lwt#772]
[ocaml-lwt for SLE_15/s390x](https://build.opensuse.org/package/show/devel:languages:ocaml/ocaml-lwt)

````
[  411s] Command [80] exited with code 1:
[  411s] $ (cd _build/default/test/unix && ./main.exe)
[  411s] Testing library 'unix'...
[  411s] .................................SSSSS.....................................................................................................SS............................................................SSF...........
[  411s]
[  411s] 2.372404 2.372402
[  411s] Test 'simultaneous' in suite 'Lwt_timeout' produced 'false'
[  411s] + echo 'dune runtest failed'
[  411s] dune runtest failed
[  411s] + test -n ''
[  411s] + echo aborting
[  411s] aborting
[  411s] + exit 1
````

Just asking for more diagnostics so one can see what might be going on.
Likely just an overloaded build VM.

**Comment by aantron** [comment]
As I understand it, these diagnostics are already enough to see that the bounds expected by the test need to be relaxed a little bit. They are currently at `2.2`:

https://github.com/ocsigen/lwt/blob/e9a9c7bde4074bd8a0cee531a7789d93628fa46e/test/unix/test_lwt_timeout.ml#L241-L244

**Comment by aantron** [comment]
Please let me know if there is something more that should be done here. I didn't see anything else that could be printed from the test; I'm not sure there is anything print from the overall runtime. The printed delays look plausibly correct, even if slower than the test expected.

**Comment by olafhering** [comment]
I have not looked at the sources, it did not occour to me that these numbers are already diagnostics.
Thanks for fixing it!
