### ISSUE TITLE
GPLed program using Lwt 

### ISSUE THREAD

**Issue by NIR-Ginko** [ocsigen/lwt#779]
I want to implement a daemon with the help of Lwt library and my manager demands the code to be GPLv2+ licensed and Lwt is MIT-licensed. Is it possible to write GPLed software using Lwt?

**Comment by aantron** [comment]
Yes, the MIT license allows usage or incorporation in a GPL project. If you vendor the code, just be sure not to lose the MIT [`LICENSE.md`](https://github.com/ocsigen/lwt/blob/master/LICENSE.md) file from the vendored copy, as the license basically only requires that a notice such as that file be preserved.

**Comment by NIR-Ginko** [comment]
Thanks!
