### ISSUE TITLE
Links to Ocaml manual with anchor are broken

### ISSUE THREAD

**Issue by tatchi** [ocsigen/lwt#781]
Links with anchor pointing to the OCaml manual seem to be broken. For instance, this one from the `lwt_io.mli` file:

`{{:https://caml.inria.fr/pub/docs/manual-ocaml/libref/Marshal.html#VALfrom_channel} [Marshal.from_channel]}`

Becomes (I guess after the doc has been generated):

`https://caml.inria.fr/pub/docs/manual-ocaml/libref/Marshal.html/#VALfrom_channel`

Note the extra `/` added before the `#`. Adding this `/` actually break the link.

**Comment by aantron** [comment]
Thanks. I moved this to ocsigen/html_of_wiki#126 with some additional info.
