### ISSUE TITLE
Lwt_unix.getlogin () fails in some environments

### ISSUE THREAD

**Issue by jakobfp** [ocsigen/lwt#791]
As mentioned in #676 & #721 `Lwt_unix.getlogin ()` fails with `ENOENT`.

I encounter this behaviour on a Debian 10 (with a 4.19 kernel) VM.

What is the reason behind the failure of `Lwt_unix.getlogin ()` in some environments ?

**Comment by aantron** [comment]
`Lwt_unix.getlogin ()` [calls](https://github.com/ocsigen/lwt/blob/0f9b94e8bc3f7b341b475263c5837a4beb1179dc/src/unix/unix_c/unix_getlogin_job.c#L25-L28) `getlogin_r(3)`, and the `ENOENT` should only be generated by the system call. From the [man page](https://www.man7.org/linux/man-pages//man3/getlogin.3.html):

```
       Linux/glibc also has:

       ENOENT There was no corresponding entry in the utmp-file.
```

I'm guessing the ultimate cause is something with your session. I recommend looking elsewhere for information on the Linux system call, and/or comparing it with the result of calling `getlogin` in C.

**Comment by jakobfp** [comment]
Alright, I see. Thanks for the hints and information.
