### ISSUE TITLE
Failing "bind: Unix domain" test on GNU/Hurd

### ISSUE THREAD

**Issue by pinotree** [ocsigen/lwt#802]
After the build fix done with #801, now the left issue to compile and test lwt successfully on GNU/Hurd is the "bind: Unix domain" test in `test/unix/test_lwt_unix.cppo.ml`.
The problem is that, because of the way the socket server (i.e. the userspace service providing Unix sockets) and the glibc implementation of sockets are, at the moment `getsockname()` on Unix sockets cannot provide the path of the bound sockets. Because of this, the end of the test
```ocaml
      try
        Lwt.return
          (chosen_path = String.sub actual_path 0 (String.length chosen_path))
      with Invalid_argument _ -> Lwt.return_false);
```
fails because `actual_path` is an empty string.
I can open a PR to fix/workaround it; however, since there are different ways to do that, I wanted to know what to do in a way acceptable for the project. Possible options are:
1. do nothing, GNU/Hurd is too niche to handle it -- understandable
2. skip the whole test on GNU/Hurd -- considering that half of the test is about checking the bound socket path, can be an option
3. skip the path comparison on GNU/hurd only
4. `Lwt.return_true` if the path is empty, on any OS
5. `Lwt.return_true` if the path is empty, on GNU/Hurd only
6. something else I'm missing

Also, in case the chosen option is to do something on GNU/Hurd only, how should the OS be checked? Neither `Sys` or `Unix` provide `uname` or an equivalent, `ExtUnix` is not used, and there is no local `uname` binding/equivalent. Simply run `uname` via `Lwt_process`?

**Comment by aantron** [comment]
Does Hurd have `/proc/version` or any other such file from which system info can be read?

**Comment by pinotree** [comment]
> Does Hurd have `/proc/version` or any other such file from which system info can be read?

There is a procfs on `/proc` which is to mimic/emulate the one from Linux:
```bash
$ cat /proc/version 
Linux version 2.6.1 (GNU 0.9 GNU-Mach 1.8+git20200710-486/Hurd-0.9 i686-AT386)
```
strictly speaking it is optional, although in Debian GNU/Hurd it is mounted by default for compatibility with existing software.

What in particular are you looking for?

**Comment by aantron** [comment]
It's probably easier to read this than to run `uname`, assuming it will be portable to enough distributions. I see `Mach` and `Hurd` in the contents that you can check for.

There may also be other Hurd-specific files.

**Comment by pinotree** [comment]
If that's the case, just checking for the top-level `/hurd/` directory should be enough.

**Comment by pinotree** [comment]
So... which approach should I take on this?

**Comment by aantron** [comment]
Checking for `/hurd`, as you suggested, seems the most convenient.
