### ISSUE TITLE
Dont_wait instead of `ignore_result`

### ISSUE THREAD

**Issue by francoisthire** [ocsigen/lwt#819]
In the Tezos codebase, we are using the function `dont_wait` instead of `ignore_result` which forces the user to handle errors:

```ocaml
let dont_wait handler f =
  let open Lwt in
  let p = apply f () in
  on_failure p handler
```

Is it welcome to have such function in `lwt.ml`? And such function could it be recommended as an alternative to `Lwt.ignore_result`? This alternative was implemented by @raphael-proust .

**Comment by aantron** [comment]
This seems like a nice and less error-prone alternative to `Lwt.async`. Note that `Lwt.ignore_result` has been not recommended for a long time, in favor of `Lwt.async`, but `dont_wait` may be even better.
