### ISSUE TITLE
Interaction between Lwt_daemon and Lwt_preemptive

### ISSUE THREAD

**Issue by smondet** [ocsigen/lwt#82]
`Lwt_preemptive.detach` stops working when calling `Lwt_daemon.demonize`

With this piece of code, `"Detached after daemon"` never gets to the log-file:

``` ocaml
let say fmt = Printf.ksprintf (Printf.eprintf "%s\n%!") fmt

open Lwt
let () =
  Lwt_main.run (
    Lwt_preemptive.detach (fun () ->
        say "Detached before daemon !") ()
    >>= fun () ->
    Lwt_log.file ~mode:`Append ~perm:0o600 ~file_name:"loooooggg-file"  ()
    >>= fun logger ->
    Lwt_daemon.daemonize ~stdout:(`Log logger) ~stderr:(`Log logger) ~directory:(Sys.getcwd ()) ();
    say "Daemonized !";
    Lwt_preemptive.detach (fun () ->
        say "Detached after daemon!") ()
    >>= fun () ->
    say "After detach";
    return ()
  )
```

EDIT: the second `Lwt_preemptive.detach` hangs by the way (does not crash or anything).

**Comment by fxfactorial** [comment]
Would be nice if doing daemonize after run could raise an exception.

**Comment by aantron** [comment]
`Lwt_daemon` is now factored out of Lwt and deprecated, so I am closing this. Please feel free to reopen if it still needs to be fixed.

See https://github.com/ocsigen/lwt/pull/484#issuecomment-338184730 about daemonization in general, and the rest of that issue for the fate of `Lwt_daemon`.
