### ISSUE TITLE
Lwt_fmt.eprintf prints to stdout instead of stderr

### ISSUE THREAD

**Issue by vog** [ocsigen/lwt#850]
The following test program:

```ocaml
let () =
  Lwt_main.run @@
  Lwt_fmt.eprintf "Test\n%!"
```

which is supposed to print into `stderr` the string "Test", followed by a newline, followed by flushing the stream, behaves as follows on the command line:

```sh
$ ./test >/dev/null
$ ./test 2>/dev/null
Test
```

So it prints into `stdout` instead of `stderr`.

The expected behavior would have been:

```sh
$ ./test >/dev/null
Test
$ ./test 2>/dev/null
```

**Comment by Drup** [comment]
Oups :S 

https://github.com/ocsigen/lwt/blob/9943ba77a5508feaea5e1fb60b011db4179f9c61/src/unix/lwt_fmt.ml#L78-L79

Would you like to submit a patch for this ? :)
