### ISSUE TITLE
Forgot to add `fix NOT_AVAILABLE stub code for Lwt_unix.send_msgto` to 5.4.1

### ISSUE THREAD

**Issue by MisterDA** [ocsigen/lwt#868]
IIUC commit https://github.com/ocsigen/lwt/commit/5ffe09f6f44eab68aad1adb933066d9e77386b19 _fix NOT_AVAILABLE stub code for Lwt_unix.send_msgto_ is a bug fix on Windows that add noop symbols for functions introduced in https://github.com/ocsigen/lwt/commit/20e8836bbbf22c27f45e5586728507c7b4ffc53b _lwt.unix: add Lwt_unix.send_msgto that takes a destination address_. I f the commit isn't present it leads to link failure on Windows, as happens with https://github.com/ocaml-community/utop/issues/356. The bug-fix wasn't included in the 5.4.1 release.
I'd suggest releasing a 5.4.2 with this patch ;)

```
Error: Error while linking C:\\Users\\antonin\\.opam\\ocaml-variants.4.12.0+mingw64c\lib\lwt\unix/lwt_unix.cma(Lwt_unix):
       The external function `lwt_unix_send_msg_byte' is not available
 ```

**Comment by raphael-proust** [comment]
I have pushed a 5.4.2 branch with this fix. I'll release next week. Thanks for the bug-report.

**Comment by raphael-proust** [comment]
https://github.com/ocaml/opam-repository/pull/19185
https://github.com/ocsigen/lwt/releases/tag/5.4.2
