### ISSUE TITLE
When using LIBEV, KQUEUE isn't chosen

### ISSUE THREAD

**Issue by rneswold** [ocsigen/lwt#87]
I run **LWT** on a **NetBSD** system. I recently submitted a patch [ocsigen/lwt/pull/79] allowing the configuration to properly recognize that `libev` is present on a system using **PKGSRC**. Now that I'm able to properly install and use it, it appears that KQUEUEs (**NetBSD**'s most efficient handle multiplexer) aren't being used. I also don't see any way for me to insist that **LWT** use KQUEUEs with `libev`.

When I installed `libev`, its config detection found `kqueue.h`, et al. **LWT**'s config now finds `libev`. But when I run my program, I see (via `top`) that it's blocking via `select`, not `kqueue` like it should be.

**Comment by yallop** [comment]
#269 adds a way to select the kqueue libev backend.
