### ISSUE TITLE
The ssl binding is not complete

### ISSUE THREAD

**Issue by jpdeplaix** [ocsigen/lwt#9]
Comparing Lwt_ssl to Ssl (https://github.com/savonet/ocaml-ssl/blob/master/src/ssl.mli), it seems to me that Lwt_ssl misses some functions (for example: open_connextion_, input__ and output_*, …).

Is it possible to complete the binding ?

**Comment by aantron** [comment]
@jpdeplaix would you be willing to add the missing functions? (no is perfectly ok :p)

**Comment by aantron** [comment]
@jpdeplaix If you don't mind, as #532 gets merged, I will close this issue. We can do any Lwt_ssl development in [aantron/lwt_ssl](https://github.com/aantron/lwt_ssl) :)

**Comment by jpdeplaix** [comment]
Ok go for it. Sorry for not having replied to your request

**Comment by aantron** [comment]
No worries, I was hassling you about working, it's fair not to reply :p
