### ISSUE TITLE
Drop support for OCaml < 4.08.0

### ISSUE THREAD

**Issue by hannesm** [ocsigen/lwt#939]
Hello,

there's quite some craft to support old OCaml releases. I'm wondering what is the reason to support old OCaml versions? Are there users thereof? Are they not fine to upgrade to a newer OCaml version? Or can't they just keep on using old Lwt releases?

Especially with OCaml 5.0.0 on the horizon, I propose to cut backwards compatibility to get rid of various dependencies on compatibility packages and code paths. What do you think? If you like the idea, I can propose a PR for this.

**Comment by raphael-proust** [comment]
I like the idea. I considered it in the past and I think that we should possibly run an informal poll on discuss just to give a chance for potential users to make themselves known.

**Comment by raphael-proust** [comment]
This is now done.

**Comment by hannesm** [comment]
Thanks @raphael-proust for your survey, and your work on reducing the dependency cone. Also thanks for preparing the 5.6 releases :)
