### ISSUE TITLE
GC pressure caused by channels created by `Lwt_ssl`

### ISSUE THREAD

**Issue by mfp** [ocsigen/lwt#98]
`write_bytes` and `read_bytes` allocate temporary string buffers in order to perform the IO using `SSL.read` and `SSL.write`, which work with strings (and not `Lwt_bytes.t`).

A preliminary fix would be to allocate one string buffer per channel (same size as the Lwt_bytes one) and reuse it.

In the long-term, it'll be nice to have a `Ssl.write_bigarray` able to work with `Lwt_bytes.t` directly.
It would also get rid of not one but two(!) copies (Ssl mallocs a buffer & copies the data there before releasing the runtime).

**Comment by Drup** [comment]
Ssl has been released with that, it seems. Can you do a PR with the fix, @mfp ?
