### ISSUE TITLE
SIGSEGV on OCaml 5 due to missing SA_ONSTACK

### ISSUE THREAD

**Issue by talex5** [ocsigen/lwt#981]
https://github.com/ocaml/ocaml/pull/11497 says:

> First commit makes sure that signal handlers are run on the alternate signal stack. This is required since fiber stacks are generally too small to run signal handlers on.

Test case:

```ocaml
open Lwt.Infix

let main () =
  for _ = 1 to 10000 do
    match Lwt_unix.fork () with
    | 0 -> Unix._exit 1
    | _child -> ()
  done

let main () =
  Lwt_main.run begin
    Lwt.pause () >>= fun () ->
    main ();
    Lwt.return_unit
  end

let () =
  Effect.Deep.match_with main ()
    { retc = ignore;
      exnc = raise;
      effc = (fun _ -> None);
    };
  Gc.full_major ()
```
Crashes with various errors, e.g.
```
$ ./_build/default/bin/main.exe 
corrupted size vs. prev_size
fish: “./_build/default/bin/main.exe” terminated by signal SIGABRT (Abort)
```
(originally reported as https://github.com/ocaml-multicore/lwt_eio/issues/15)

**Comment by talex5** [comment]
Are you able to reproduce this? I've seen it on multiple machines.

**Comment by raphael-proust** [comment]
I haven't tried reproducing yet. I'm planning on spending some time on Lwt in not too long to get a release through but I don't know when exactly yet.
